### ISSUE TITLE
目录结构问题

### ISSUE THREAD

**Issue by conan2008** [kailong321200875/vue-element-plus-admin#1]
感谢开源架构！

请问业务代码为什么要放在 pages/index下，  这个index有什么特殊意义么？

**Comment by kailong321200875** [comment]
> 感谢开源架构！
> 
> 请问业务代码为什么要放在 pages/index下， 这个index有什么特殊意义么？

因为这套系统当初设计的时候是准备采用多页模式的，所以pages里面的子目录其实就是相当于一个单独的页面，如果你不需要多页的话，那pages/index的，其实就相当于我们最开始使用的单页模式，就是当前结构就是多了几层而已，并不影响使用。
