### ISSUE TITLE
setValue() is not a defined function in example dialog page.

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#102]
Hello @kailong321200875 
I forked example dialog page and should set some string to a input component.
I can get form data using getFormData() but setValue() is not a defined function here.
I logged write but it doesn't have a methods.
What's wrong?
![image](https://user-images.githubusercontent.com/103615256/177001067-71cb67d9-deaa-4ea8-9cf1-3089c7aacd9e.png)

**Comment by kailong321200875** [comment]
Because the corresponding method is not exported
![image](https://user-images.githubusercontent.com/32283845/177019771-4338f836-30cd-4a37-9ec4-c089a4a3cf8e.png)
