### ISSUE TITLE
How to use useValidator

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#103]
Hello @kailong321200875 
I tried to use useValidator to validate it's mobile number or not.
Like here.
![image](https://user-images.githubusercontent.com/103615256/177002066-4a55f0b3-3b3c-4a76-a523-a546f2bf360a.png)

But I'm not sure how I can use this func, especially parameters.

![image](https://user-images.githubusercontent.com/103615256/177002047-e479ca93-ebae-4df5-ba18-b5cc3cd4d858.png)

How can I fix?

**Comment by kailong321200875** [comment]
![image](https://user-images.githubusercontent.com/32283845/177019720-15357085-c5a2-44f1-81b5-0c2e9c98ba88.png)
