### ISSUE TITLE
Proxy api is not working in deployment

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#104]
Hello @kailong321200875 
Thank you for your kind responses.

I tried to deploy my project on vercel and it's done.
But the api is not working.
vite.config.ts
![image](https://user-images.githubusercontent.com/103615256/177034592-5e2a9364-386b-4f77-8a94-0376bc350194.png)

src/config/axios/config.ts
![image](https://user-images.githubusercontent.com/103615256/177034618-10ba24ac-e5fa-48e2-862d-23f8e062db99.png)

When I try to make a request in deployed website, 404 error is occured.
![image](https://user-images.githubusercontent.com/103615256/177034629-356fb8e7-afe5-401b-91b9-4578e3bd6417.png)

How can I fix?

**Comment by kailong321200875** [comment]
base: '/api'，That's right

**Comment by silverbasilisk** [comment]
Hello @kailong321200875 
I deployed pro not base.
And you mean that use '/api' instead of 'api'?
