### ISSUE TITLE
How to change height in Dialog

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#106]
Hello @kailong321200875 
I hope you had a good weekend.
And I'd like to change the height of dialog because it has only fixed height without necessary. Like this.
![image](https://user-images.githubusercontent.com/103615256/177063420-c858eca6-8a0a-411d-8d3b-002c25ecd9dc.png)

**Comment by kailong321200875** [comment]
If you don't need it, please change it yourself in the src/components/Dialog directory
