### ISSUE TITLE
Prepend in AutoComplete

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#108]
Hello @kailong321200875 
I have an issue in using an AutoComplete component.
I need to show dropdown with HEADER like this one.

![image](https://user-images.githubusercontent.com/103615256/177398361-6bfdcdb1-258e-48a8-a94c-6806f681586f.png)

But I can't handle the header like above.

![image](https://user-images.githubusercontent.com/103615256/177398285-603ab359-6cdf-4be4-b540-d9524616644e.png)

How can I fix?

**Comment by kailong321200875** [comment]
This should be handled by yourself
