### ISSUE TITLE
api is not working in formSchema

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#109]
Hello @kailong321200875 
I tried to use api option in Select component to fetch options from backend directly.
But there is no request.
I used formSchema and useForm hook.
![image](https://user-images.githubusercontent.com/103615256/177403191-8f06475e-8160-42b1-bfe4-48811748f038.png)

What's wrong?

**Comment by kailong321200875** [comment]
It can only be used in usecurdschemas
