### ISSUE TITLE
define v-model in component in formSchema

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#110]
Hello @kailong321200875 
Actually I used to use React.js and Vue.js is first for me.
And I'd like to declare variable like Ref and v-model in Schema to handle in script setup.
For example there are two components type and list like following
![image](https://user-images.githubusercontent.com/103615256/177416794-1e407764-debc-46f3-8e15-40e20a93b32b.png)
The list in the right should be changed along the type.
But I have no solution to do this now.
Only thing I can do is to get value using getFormData() from whole schema when radio is changed and then execute setSchemaOption().
I think this is not the best solution.
How can I fix?

**Comment by kailong321200875** [comment]
you can use componentProps: { onChange: (val: any) => { // to do something } }
