### ISSUE TITLE
Can I make the orders of component in  search form from table order in CRUD schema?

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#111]
Hello @kailong321200875 
CRUD Schema you created is very smart and intelligent so it's very convenient to use.
And I'd like to know how to change the orders in search bar.
For example the order in table is A, B, C, D and the order in search form is B, A, D, C.
Is this possible in CRUD Schema?

**Comment by kailong321200875** [comment]
Currently not supported

**Comment by tinyice123** [comment]
abcd

**Comment by tinyice123** [comment]
haha

**Comment by silverbasilisk** [comment]
@tinyice123 
What's up?
