### ISSUE TITLE
Router.replace() is not working well

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#114]
Hello @kailong321200875 
I'd like to go to `/login` when the session is expired in the backend side.
But below code works sometimes but not other times.
In case of not working, router.replace() only changes the value of url in browser link bar, not execute.
How can I fix?
```
// response 拦截器
service.interceptors.response.use(
  (response: AxiosResponse<Recordable>) => {
    console.log(response.data)
    if (response.data.code === result_code) {
      return response
    } else if (response.data.code === 401 && response.data.msg === '登陆过期！') {
      wsCache.clear()
      tagsViewStore.delAllViews()
      resetRouter() // 重置静态路由表
      router.replace({
        path: '/login'
      })
    } else {
      ElMessage.error(response.data.msg)
    }
  },
  (error: AxiosError) => {
    console.log('err' + error) // for debug
    ElMessage.error(error.message)
    return Promise.reject(error)
  }
)

```

**Comment by kailong321200875** [comment]
Is there a detailed error report

**Comment by silverbasilisk** [comment]
Yes, I have.
For example I used select component for '檢索姓名/檔案號/拼音/手機號' with api in the following page.
![image](https://user-images.githubusercontent.com/103615256/181401891-6f2aeb06-9634-4cba-b6b7-16eac9765834.png)

I think it's navigated when the response code is 401 by above [code](https://github.com/kailong321200875/vue-element-plus-admin/issues/114#issue-1295266560).
But it's only replace link, not execute navigating, like this.
![image](https://user-images.githubusercontent.com/103615256/181402167-ac9bd2cf-02d7-4bf2-8bda-6645b6751103.png)

What's wrong with this?
How can I fix?
