### ISSUE TITLE
非常棒的项目，作者有考虑建立交流群吗

### ISSUE THREAD

**Issue by jiangyitao** [kailong321200875/vue-element-plus-admin#12]
RT

**Comment by kailong321200875** [comment]
@jiangyitao 这个可能暂时还不考虑吧，目前使用基数比较小，可能会变成死群。所以还是建议先用issues来反馈问题

**Comment by jiangyitao** [comment]
> @jiangyitao 这个可能暂时还不考虑吧，目前使用基数比较小，可能会变成死群。所以还是建议先用issues来反馈问题

期待早日建立沟通渠道
