### ISSUE TITLE
关于项目第一次进入加载及项目刷新加载时间过长问题

### ISSUE THREAD

**Issue by 2624431797** [kailong321200875/vue-element-plus-admin#123]
如下图，第一次加载时间达到了2分钟，刷新项目也是时间蛮长的，是否该使用按需加载呢，实际业务开发中加载时间过长对用户体验不好
![P5NO7o3zez](https://user-images.githubusercontent.com/54942617/180163551-3a4182e5-5765-49b4-8173-d301b351dcab.jpg)
![6EoVWqYRNl](https://user-images.githubusercontent.com/54942617/180163609-0f62c05d-5174-493c-a1bc-e5e94e0ebdaa.jpg)

**Comment by kailong321200875** [comment]
这其实目前没有太好的办法，因为vite他是冷启动，简单点理解就是说他起一个服务很快，但是每个模块他还是要按需加载的，这也就导致了如果你的依赖过多的话，他会先去加载所需的资源。
