### ISSUE TITLE
ts校验问题

### ISSUE THREAD

**Issue by williamLQX** [kailong321200875/vue-element-plus-admin#124]
作者您好
文件路径：utils/routerHelper.ts。 158行
![1831658456412_ pic](https://user-images.githubusercontent.com/105276842/180348887-ac7e2ebd-aa6e-44e9-8a62-08c60b9cb014.jpg)
git commit 的时候因为有ts:check，所以不能完成commit，这是为什么？

**Comment by kailong321200875** [comment]
可以看下最新的master代码
