### ISSUE TITLE
登录路由跳转问题

### ISSUE THREAD

**Issue by williamLQX** [kailong321200875/vue-element-plus-admin#125]
作者您好
登录页面，登录成功之后想前端控制路由菜单渲染。我没有走菜单的接口
![image](https://user-images.githubusercontent.com/105276842/180695189-e31b4234-430b-4a80-88c9-f19777a7f164.png)
直接在这写死了，但是点击登录报错了
<img width="683" alt="image" src="https://user-images.githubusercontent.com/105276842/180695221-6bef962c-fe0a-4a29-9e12-4e5fbb03a16b.png">
这是什么问题呢？

**Comment by williamLQX** [comment]
已解决，是因为404页面没有被注册

**Comment by kailong321200875** [comment]
https://github.com/kailong321200875/vue-element-plus-admin/commit/55522b0661a8df3ad3c8afafcc9f8fcb162c5a00

具体可以查看下这部分的记录，已做了一个示例
