### ISSUE TITLE
饼图数据不更新

### ISSUE THREAD

**Issue by deakintsang** [kailong321200875/vue-element-plus-admin#126]
饼图调用API拿到数据后并没有更新图表，柱图却是可以

![image](https://user-images.githubusercontent.com/35422654/181205403-0c0ecbbc-b57f-4183-b8cd-4cb380874d68.png)

![image](https://user-images.githubusercontent.com/35422654/181206407-895d6f9c-b3b3-447d-a249-f3dc6189ee25.png)

**Comment by kailong321200875** [comment]
已修复
