### ISSUE TITLE
在路由meta中设置了hidden: true，使用push跳转到404

### ISSUE THREAD

**Issue by mabobj** [kailong321200875/vue-element-plus-admin#128]
1、在路由meta中设置了hidden: true，在左侧菜单不显示
2、在其他页面使用push({ path: '***' })，会跳转到404
3、把路由中hidden: true去掉，再使用push即可跳转到目标页面

请问是哪里配置不正确吗？

**Comment by kailong321200875** [comment]
请确保path 是一个完整路径，完整路径必须是以 / 开头的
