### ISSUE TITLE
修改主题色问题

### ISSUE THREAD

**Issue by williamLQX** [kailong321200875/vue-element-plus-admin#129]
作者你好
我按照项目上面有一个能修改主题色变量，修改完之后按钮的主题确实是变了，但是鼠标移上去的hover背景色并没有变是什么问题
![image](https://user-images.githubusercontent.com/105276842/181442081-0a6822c3-d2da-4f29-89d0-fc41330b3afd.png)

**Comment by kailong321200875** [comment]
这个我看下，是不是element-plus做了啥

**Comment by kailong321200875** [comment]
这个是element-plus的BUG应该，需要等官方修复下
