### ISSUE TITLE
可否提供一个scss版本

### ISSUE THREAD

**Issue by oui-a11y** [kailong321200875/vue-element-plus-admin#130]
可否提供一个scss版本，或者由less更新为scss需要那些操作？ ele-plus为cscc 想统一

**Comment by kailong321200875** [comment]
vite已经内置了scss了，所以只需要把语言改成scss基本上就可以了，目前项目中用的比较多的是css变量，less变量相对较少，可以搜索一下less变量的前缀，换成scss的前缀应该就行了。

**Comment by hellorayza** [comment]
Considering that the upstream project uses Sass, I have provided [a copy that using Sass](https://github.com/hellorayza/vue-element-plus-admin) here.

If the author wants to merge or maintain a new branch, you can use this fork.
