### ISSUE TITLE
Can I set component show or hidden using schema?

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#133]
Hello @kailong321200875 
Is it possible to set component show or hidden using schema?
If so how can I do?

**Comment by silverbasilisk** [comment]
Actually, I am doing this like following.
```
const spanRef = ref(8)
const schema = [
  {
    ...
    colProps: {
      span: spanRef
    }
    ...
  }, 
  {
    ...
    onChange: (item) => {
      spanRef.value = (item === 'Y' ? 8 : 0)
    }
    ...
  }
]
```

Or like this.
```
schema[0]?.colProps?.span = 8
```

But this is not good solution I think.
Is there no way to do like v-if?
Let me know the better.

**Comment by kailong321200875** [comment]
you can  set hidden: true
