### ISSUE TITLE
Set component hidden is not working well

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#134]
Hello @kailong321200875 
Thank  you for your reply and I tried with your solution.
But it's not working well like this.
![image](https://user-images.githubusercontent.com/103615256/182072537-d3fe8913-4452-4850-b205-aa551ebbe229.png)

The code is
```
componentProps: {
  hidden: true
}
```

I also tried like this
```
componentProps: {
  style: { display: 'none' }
}
```
But it hides only component not label like this.
![image](https://user-images.githubusercontent.com/103615256/182072908-cd6296d6-adaa-43d0-bdc0-ed2141f3d69f.png)

How to hide component with label easily?

**Comment by kailong321200875** [comment]
{
    ...
    colProps: {
      span: spanRef
    },
    hidden: true
    ...
  }

That's right
