### ISSUE TITLE
默认关闭tagView的情况下footer下面有空白

### ISSUE THREAD

**Issue by zhengfan0829** [kailong321200875/vue-element-plus-admin#137]
![image](https://user-images.githubusercontent.com/29992178/182132501-2c22f725-7cbe-47e5-bddf-3147363c0756.png)

另外问一下，表格的数据操作，例如删除必须要经过表格组件的内部逻辑吗？

**Comment by kailong321200875** [comment]
空白的无法复现，表格的操作的话，基本上都是走内部逻辑，如果不需要的话，可以重写一下
