### ISSUE TITLE
打开多个TagsView时会报错，用的 template 分支

### ISSUE THREAD

**Issue by zymapp** [kailong321200875/vue-element-plus-admin#142]
错误如下： 
Cannot read properties of undefined (reading 'offsetLeft')
    at moveToTarget (TagsView.vue:154:40)
    at moveToCurrentTag (TagsView.vue:107:9)

![1](https://user-images.githubusercontent.com/30652064/184340225-db2e8cfb-42ea-4e1a-bba4-1522c02f0fcb.png)

**Comment by kailong321200875** [comment]
template已经不准备维护了，没有太多精力维护这个分支
