### ISSUE TITLE
点击面包屑时，如果不是叶子节点会出现空白页

### ISSUE THREAD

**Issue by Jenyow** [kailong321200875/vue-element-plus-admin#146]
在线预览里可以重现
![image](https://user-images.githubusercontent.com/7712958/184894861-9a62873c-24b2-40e0-bc32-6495bef3bcc3.png)

![image](https://user-images.githubusercontent.com/7712958/184894938-704949c2-154f-4827-bf05-48cd942fd156.png)

**Comment by kailong321200875** [comment]
已处理
