### ISSUE TITLE
示例弹窗新增窗口组件渲染错误

### ISSUE THREAD

**Issue by irspgc** [kailong321200875/vue-element-plus-admin#147]
点击详情页后，再点击新增组件渲染错误
![图片](https://user-images.githubusercontent.com/53424621/185056165-d5ea4b9d-0896-4ff6-b307-650d9689718d.png)

**Comment by kailong321200875** [comment]
无法复现，请提供另外的详细信息，如admin 的版本，运行环境等

**Comment by kailong321200875** [comment]
已处理
