### ISSUE TITLE
How to deploy to vercel

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#151]
How can I deploy to vercel?
![image](https://user-images.githubusercontent.com/103615256/185830721-daf6eb1a-9bdf-44ef-8c0a-2e60b4dcd520.png)

Is this settings right?

**Comment by kailong321200875** [comment]
see: https://element-plus-admin-doc.cn/guide/deploy.html#%E5%8F%91%E5%B8%83

**Comment by silverbasilisk** [comment]
Have you ever deployed to vercel?
