### ISSUE TITLE
部分页面打开时报错，例如引导页、综合示例-页面

### ISSUE THREAD

**Issue by minibill11** [kailong321200875/vue-element-plus-admin#152]
最新代码1.6.3，使用vscode正常执行pnpm install，pnpm run dev启动

打开引导页面报错误：
[vite] Internal server error: unplugin-vue-macros SyntaxError: Unexpected token (1:0)
![image](https://user-images.githubusercontent.com/25745175/186087024-940b945c-e940-4414-8efe-a39d16f076ae.png)

打开综合示例-页面 和 多级菜单页面 报错误：
[vite] Internal server error: unplugin-vue-macros Error: [@vue/compiler-sfc] SFC contains no <script> tags.
![image](https://user-images.githubusercontent.com/25745175/186087131-0c368d04-080e-4f07-a062-9d7981fde092.png)

浏览器控制台：
![image](https://user-images.githubusercontent.com/25745175/186088334-f8ab4a1f-b3dd-4739-ab65-bd2db6ecf4c7.png)

其中综合示例-页面 和 多级菜单页面在代码中注释掉 页面缓存相关的 defineOptions部分就可以正常运行
![image](https://user-images.githubusercontent.com/25745175/186087848-f79a8995-a286-4c1a-b8bf-7ddf0c04b976.png)

**Comment by wushaoge** [comment]
+1，碰到相同的问题

**Comment by hzzdong** [comment]
+1，碰到相同的问题

**Comment by kailong321200875** [comment]
已处理
