### ISSUE TITLE
windows 克隆下来 pnpm i 不成功

### ISSUE THREAD

**Issue by qzzm** [kailong321200875/vue-element-plus-admin#153]
windows11   nodejs 16.17  pnpm7.9.3  安装包报错以下错误 怎么解决呢

**no such file or directory, stat 'E:\project\test\eladmin\node_modules\.pnpm\registry.npmmirror.com+@commitlint+cli@17.0.3\node_modules\execa'**

` WARN  deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
 WARN  deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
 WARN  deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
 WARN  deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
 WARN  deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
 WARN  deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
Packages: +946
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 ENOENT  ENOENT: no such file or directory, stat 'E:\project\test\eladmin\node_modules\.pnpm\registry.npmmirror.com+@commitlint+cli@17.0.3\node_modules\execa'

pnpm: ENOENT: no such file or directory, stat 'E:\project\test\eladmin\node_modules\.pnpm\registry.npmmirror.com+@commitlint+cli@17.0.3\node_modules\execa'
Progress: resolved 966, reused 945, downloaded 0, added 0
PS E:\project\test\eladmin> 
`

**Comment by kailong321200875** [comment]
尝试着把node换成16.0.0看看

**Comment by qzzm** [comment]
> 尝试着把node换成16.0.0看看

今日刚试win降版本为16.0.0 还是一样的错误，不知道是不是win11的问题 改日试下win10
目前win下使用 npm 或 yarn用能正常运行      pnpm在macosx 10.15  10.14均正常

**Comment by kailong321200875** [comment]
因为我这边没有win11的系统，所以这个问题可能没办法去处理
