### ISSUE TITLE
路由缓存有问题

### ISSUE THREAD

**Issue by wushaoge** [kailong321200875/vue-element-plus-admin#154]
复现方式：
noCache设置为false, 从列表跳转同一个详情
第一次点击用户详情跳转   xxx/userDetail?userId = 1 , 这时候点击切换tag没问题
第二次点击另外一个用户详情跳转   xxx/userDetail?userId = 2   跳转没问题
如果这时候切换tag再切换回来  变成了第一次的xxx/userDetail?userId = 1的缓存
貌似只会缓存第一次的页面内容

**Comment by kailong321200875** [comment]
因为对于路由来说，你的路由确实是没变化的，只是query变化了。这个可能得自己watch一下

**Comment by ma6566966** [comment]
解决了吗
