### ISSUE TITLE
想问一下, 新建组件怎么给父级传值

### ISSUE THREAD

**Issue by laojiangshi** [kailong321200875/vue-element-plus-admin#157]
制作了上传组件, 不知道怎么把得到的路径传给父级.  能完善下文档吗?  已经按文档注册了组件,获取获得到了上传文件的路径.

`const handleAvatarSuccess: UploadProps['onSuccess'] = (
  response, // 实际返回的图片路径
  uploadFile
) => {
  imageUrl.value = URL.createObjectURL(uploadFile.raw!)
//   console.log(response)
//   getImageUrl.value = response
//   ValueImageUrl.value = response
//   return response
怎么返回给父级啊?

}`

**Comment by kailong321200875** [comment]
子组件传值给父组件，要用事件发射

**Comment by jashok2** [comment]
https://cn.vuejs.org/guide/components/provide-inject.html
vue3官方文档，依赖注入，是否是你想要的
