### ISSUE TITLE
关于 FormSchema 的 componentProps 的 slots参数

### ISSUE THREAD

**Issue by x19990416** [kailong321200875/vue-element-plus-admin#158]
我看源码有一个 slots 参数 

    // 表单组件属性，slots对应的是表单组件的插槽，规则：${field}-xxx，具体可以查看element-plus文档
    componentProps?: { slots?: Recordable } & ComponentProps

具体该怎么配置呢？

有没有具体的例子呀

**Comment by laojiangshi** [comment]
同样的问题, 关键这个插槽 我也没看懂怎么用

**Comment by kailong321200875** [comment]
<img width="902" alt="image" src="https://user-images.githubusercontent.com/32283845/191402474-ebb7eb52-a651-40ec-ace6-9f95e1e80ab0.png">
<img width="667" alt="image" src="https://user-images.githubusercontent.com/32283845/191402525-f8b632b8-8db5-4435-9bb3-9b889d22eb41.png">
可以看下 http://localhost:4000/#/components/form/default-form 全部例子
