### ISSUE TITLE
本地启动有2个报错，一个mock路径，一个操作不被允许

### ISSUE THREAD

**Issue by hezhichun** [kailong321200875/vue-element-plus-admin#161]
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/20147613/188295167-8a08150b-03d0-4f2c-8ae9-5663292554c2.png">

能打开页面，但无法mock登录

![Uploading image.png…]()

**Comment by hezhichun** [comment]
<img width="956" alt="image" src="https://user-images.githubusercontent.com/20147613/188295286-a8a1ae98-c8d2-4e42-b5e1-3747bccb5668.png">

<img width="520" alt="image" src="https://user-images.githubusercontent.com/20147613/188295295-c54fdf52-3c56-4c64-85c9-0f79baab6059.png">

能启动，但有报错，无法mock，是mac 系统

**Comment by kailong321200875** [comment]
无法复现，请确保项目路径不带有中文，并且使用pnpm安装。
