### ISSUE TITLE
npm i 安装报错，加上--legacy-peer-deps才能正常安装

### ISSUE THREAD

**Issue by plftzk** [kailong321200875/vue-element-plus-admin#163]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: vue-element-plus-admin@1.6.3
npm ERR! Found: vue@3.2.37
npm ERR! node_modules/vue
npm ERR!   vue@"3.2.37" from the root project
npm ERR!   peer vue@"^2.6.14 || ^3.2.0" from pinia@2.0.22
npm ERR!   node_modules/pinia
npm ERR!     pinia@"^2.0.21" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.0
npm ERR! node_modules/@vue/composition-api
npm ERR!   peerOptional @vue/composition-api@"^1.4.0" from pinia@2.0.22
npm ERR!   node_modules/pinia
npm ERR!     pinia@"^2.0.21" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by kailong321200875** [comment]
建议只使用pnpm
