### ISSUE TITLE
线上打包问题

### ISSUE THREAD

**Issue by williamLQX** [kailong321200875/vue-element-plus-admin#166]
你好，我进行线上打包的时候出现了错误，
<img width="966" alt="image" src="https://user-images.githubusercontent.com/105276842/191462585-7cc6fc79-7616-435f-8f27-f7eaaf5800f5.png">
本地打包没有问题，线上打包的时候直接卡死在这了，能帮忙看一下嘛？

**Comment by kailong321200875** [comment]
我这里并没有出现你这种情况，有没有可能是内存不够的问题。或者你把依赖都升级一下看看

**Comment by williamLQX** [comment]
找到问题了，是vite配置中的一个参数，build的时候minify设置为'esbuild'就没有这个问题，如果是terser就会有那个问题。

**Comment by kailong321200875** [comment]
找到问题就行
