### ISSUE TITLE
CrudFormParams 配置api 远程访问不起作用

### ISSUE THREAD

**Issue by diorslau** [kailong321200875/vue-element-plus-admin#169]
form: {
      component: 'Select',
      api: getProductAllApi,
      componentProps: {
        optionsAlias: {
          labelField: 'name',
          valueField: 'id'
        }
      }
    }

如题,  配置api 后  打开form 并没有请求这个api 方法,  请问具体要怎么使用呢

**Comment by kailong321200875** [comment]
<img width="615" alt="image" src="https://user-images.githubusercontent.com/32283845/193176979-d69df2eb-c159-47df-8a08-c5b237f72abb.png">
需要自己返回数据
