### ISSUE TITLE
使用router.addRoute()添加新路由后，router.push()后，左侧菜单页面没有更新应该怎么操作？

### ISSUE THREAD

**Issue by wenlongFam** [kailong321200875/vue-element-plus-admin#170]
版主你好，我使用vue-element-plus-admin框架,router.addRoute()添加新路由后，router.push()跳转新导航，左侧菜单页面没有更新应该怎么操作？

**Comment by kailong321200875** [comment]
就正常跳转就可以了，确保路径是正确的，可能你要贴下你的代码才行，我这边测试是没问题的

**Comment by wenlongFam** [comment]
`// 新建系统
const xjxitin = () => {
  tjxtzd.projectId = projectid.value
  tianjiaxt.value = true

  console.log(permissionStore);

  //添加系统3 路由
  router.addRoute('Duolianjixitong', {
    path: '/projectbrowsing/duolianjixitong/xitong/id=3',
    component: () => import('@/views/Projectbrowsing/duolianjixitong/xitong/systemTabShow.vue'),
    name: 'Xitong3',
    meta: {
      title: t('routers.xtyc3'),
    }
  })
  router.push("/projectbrowsing/duolianjixitong/xitong/id=1")//这里正常跳转
}`

**Comment by kailong321200875** [comment]
你需要generateRoutes调用这个方法，并且把浏览器缓存中的值也改成最新的，可以参考下登录那一块的逻辑。

**Comment by wenlongFam** [comment]
![image](https://user-images.githubusercontent.com/45864590/194744990-b4bc09e8-7ae0-4ff8-b107-52e4b82ed370.png)
`// 新建系统
const xjxitin = () => {
  tjxtzd.projectId = projectid.value
  tianjiaxt.value = true

  //添加系统3 路由
  // router.addRoute('Duolianjixitong', {
  //   path: '/projectbrowsing/duolianjixitong/xitong/id=3',
  //   component: () => import('@/views/Projectbrowsing/duolianjixitong/xitong/systemTabShow.vue'),
  //   name: 'Xitong3',
  //   meta: {
  //     title: t('routers.xtyc3'),
  //   }
  // })

  permissionStore.getAddRouters.forEach((route) => {
    console.log(route);//这里要push要增加的路由对象吗
    
  }) // 动态添加可访问路由表  
  permissionStore.setIsAddRouters(true)
  router.push("/projectbrowsing/duolianjixitong/xitong/id=1")
}`

**Comment by wenlongFam** [comment]
![image](https://user-images.githubusercontent.com/45864590/194745684-1a47a8b1-b0f0-4989-9021-171e1ff9dd52.png)
这样修改不行，
    formData.account === 'admin'
      ? await permissionStore.generateRoutes('admin', routers).catch(() => {})
      : await permissionStore.generateRoutes('test', routers).catch(() => {})
这个代码是权限的，我暂时没有用到，只做菜单的。

`// 新建系统
const xjxitin = () => {
  tjxtzd.projectId = projectid.value
  tianjiaxt.value = true

  permissionStore.getAddRouters.forEach((route) => {
    router.addRoute(route as RouteRecordRaw)
    if(route.name === "Projectbrowsing"){
      router.addRoute(
        {
          path: '/projectbrowsing/duolianjixitong/xitong/id=2',
          component: () => import('@/views/Projectbrowsing/duolianjixitong/xitong/systemTabShow.vue'),
          name: 'Xitong2',
          meta: {
            title: t('routers.xtyc2'),
          }
        }
        )
    }
    
  })
  permissionStore.setIsAddRouters(true)
  router.push("/projectbrowsing/duolianjixitong/xitong/id=1")
}`

**Comment by kailong321200875** [comment]
@wenlongFam 你可以在原有的 generateRoutes 的基础上去改成你想要的，你目前这样写看起来是有问题的

**Comment by wenlongFam** [comment]
版主你好：
在generateRoutes的基础上修改了代码，可以增加菜单了，但又有一个新问题，打开添加的页面路由，没有页面顶部和左侧布局，是什么问题？

**这是代码：**

**增加菜单按钮**
`//增加菜单按钮
const addRouteBtn = () => {
  //新系统路由内容
  const roleRouters = wsCache.get('roleRouters') || []
    const systemRoute = {
      path: 'test',
      component: () => import('@/views/Dashboard/Workplace.vue'),
      name: 'Test',
      meta: {
        title: "测试"
      }
    }
    router.addRoute({
      path: '/dashboard/test',
      component: () => import('@/views/Dashboard/Workplace.vue'),
      name: 'Test',
      meta: {
        title: "测试"
      }
    })
    //添加新系统路由
    permissionStore.generateRoutes(
      'addSystemRoute',
      roleRouters as AppCustomRouteRecordRaw[],
      systemRoute
    )
}`

**permission.ts文件**
`generateRoutes(
      type: 'admin' | 'test' | 'none' | 'addSystemRoute',
      routers?: AppCustomRouteRecordRaw[] | string[],
      systemRoute?: AppCustomRouteRecordRaw[] | string[]
    ): Promise<unknown> {
      return new Promise<void>((resolve) => {
        let routerMap: AppRouteRecordRaw[] = []
        if (type === 'admin') {
          // 模拟后端过滤菜单
          routerMap = generateRoutesFn2(routers as AppCustomRouteRecordRaw[])
        } else if (type === 'test') {
          // 模拟前端过滤菜单
          routerMap = generateRoutesFn1(cloneDeep(asyncRouterMap), routers as string[])
        } else {
          // 直接读取静态路由表
          routerMap = cloneDeep(asyncRouterMap)
          //增加新路由新系统选项
          if(type === "addSystemRoute"){
            routerMap.forEach((item) => {
              console.log(item);
              if (item.name == "Dashboard") {
                item.children.push(
                  systemRoute
                )
              }
            })
          }
        }
        // 动态路由，404一定要放到最后面
        this.addRouters = routerMap.concat([
          {
            path: '/:path(.*)*',
            redirect: '/404',
            name: '404Page',
            meta: {
              hidden: true,
              breadcrumb: false
            }
          }
        ])
        // 渲染菜单的所有路由
        this.routers = cloneDeep(constantRouterMap).concat(routerMap)
        resolve()
      })
    },`

![1](https://user-images.githubusercontent.com/45864590/194852912-cdef49d2-1930-4625-8d8e-39341735ea30.png)
![permission ts](https://user-images.githubusercontent.com/45864590/194852928-4febb5d0-245d-48dc-8e24-342289f52351.png)
![2](https://user-images.githubusercontent.com/45864590/194852879-01f1a3ec-3b9a-4076-8eeb-8a3c63d513a1.png)

**Comment by wenlongFam** [comment]
是不是push的路由没有继承  父级的 component: Layout,？
![image](https://user-images.githubusercontent.com/45864590/194979755-d68ea10b-e679-4e50-a4ef-c0eff8ae2799.png)

**Comment by wenlongFam** [comment]
**我在permission.ts的generateRoutes函数里增加：**
`//添加系统路由
      addRoute({
        path: '/projectbrowsing/duolianjixitong/xitong/id=2',
        component: () => import('@/views/Projectbrowsing/duolianjixitong/xitong/systemTabShow.vue'),
        name: 'Xitong2',
        meta: {
          title: "Xitong2"
        }
      })`

**报错，**
permission.ts:9 
       Uncaught TypeError: Cannot destructure property 'addRoute' of 'useRouter(...)' as it is undefined.
![image](https://user-images.githubusercontent.com/45864590/195013244-0fdec112-3b91-45ee-9c3c-9a127ce038d1.png)

**Comment by wenlongFam** [comment]
`// 渲染菜单的所有路由 + 新系统路由
          const oldRoutes = cloneDeep(constantRouterMap).concat(routerMap)
          oldRoutes.forEach((item) => {
            if(item.name == "Projectbrowsing"){
              item.children.forEach((itemChildren) => {
                if(itemChildren.name == "Duolianjixitong"){
                  itemChildren.children?.push(routeItem)
                }
              })
            }
          })
          //console.log(oldRoutes);//数据正确
          this.routers = reactive(oldRoutes)`
![4201589610-63456b2649a38](https://user-images.githubusercontent.com/45864590/195104240-b61e3940-efb2-4c4b-ab46-e16c8af2d666.png)

**打开页面缺少 顶部和左侧布局，**
![222](https://user-images.githubusercontent.com/45864590/195104269-38f8d76f-e856-4b1c-bdbd-19ccf1c49c2a.png)

**Comment by wenlongFam** [comment]
好像是没继承父级的Layout组件。怎么搞，

**Comment by kailong321200875** [comment]
<img width="802" alt="image" src="https://user-images.githubusercontent.com/32283845/195307441-9ffbec45-d64f-4dc3-8a2e-7143fb221304.png">

<img width="880" alt="image" src="https://user-images.githubusercontent.com/32283845/195307513-b63b25d5-209c-4a53-8569-fadf2bfa1042.png">

addRoute 应该是要他的上一级，而不是他本身，不然会当做是一个一级路由处理

**Comment by kailong321200875** [comment]
@wenlongFam

**Comment by wenlongFam** [comment]
版主，permissionStore.generateRoutes2()函数是什么？

**Comment by kailong321200875** [comment]
就是我自己写的一个demo，你应该也用不上

**Comment by wenlongFam** [comment]
我按照上面的代码写菜单没出来。

**Comment by kailong321200875** [comment]
我把我写的demo给你参考下，稍等

**Comment by kailong321200875** [comment]
<img width="584" alt="image" src="https://user-images.githubusercontent.com/32283845/195490551-a16d0fc7-0b7d-4b94-85e9-ac05f2b18d42.png">

**Comment by wenlongFam** [comment]
不好意思，版主，首先感谢百忙之中抽时间来做demo，还有一点小问题，我添加的是第3级路由，我按您的方法，加上后的内容页面有点问题，您再看看。
![1](https://user-images.githubusercontent.com/45864590/195549677-dd3a82ca-ecf7-4d8e-8254-6db608da6ec3.png)
![2](https://user-images.githubusercontent.com/45864590/195549785-0384fefc-2336-4b6a-a3d0-0c9073246ac3.png)
![3](https://user-images.githubusercontent.com/45864590/195550379-e7e54267-9aa3-4999-b3c9-5d2e2c863eee.png)

**Comment by wenlongFam** [comment]
版主，不好意思，首先感谢为这个功能做demo，现在还有1个小问题，我现在添加的是第3级路由，打开页面后的内容不对，您再看看。
![1](https://user-images.githubusercontent.com/45864590/195565875-8bdd6511-9c87-4b14-9a91-14ff8fa61070.png)
![2](https://user-images.githubusercontent.com/45864590/195565915-a5446e38-9ac8-4fa6-a01b-3ebe33460426.png)
![3](https://user-images.githubusercontent.com/45864590/195565947-0461cf60-7637-401c-8f20-c04ab00b1ba9.png)

**Comment by wenlongFam** [comment]
![1](https://user-images.githubusercontent.com/45864590/195755999-14921a95-6f70-47ee-8ac6-6c48a865e9f7.png)
看路由数据是正常的。

**Comment by wenlongFam** [comment]
在第2级下添加路由有问题，在Level的Menu1下添加路由，

报警告：
[Vue warn]: Component is missing template or render function. 并且页面是空白，

![1](https://user-images.githubusercontent.com/45864590/196035093-c7d24a3e-5895-4675-a720-9fc8cbf1b272.png)
![2](https://user-images.githubusercontent.com/45864590/196035099-ebf8996e-aa3a-4e9a-a2d7-d6841a0c291b.png)
![3](https://user-images.githubusercontent.com/45864590/196035103-43066255-7b4f-407d-aef8-208836574504.png)

**Comment by wenlongFam** [comment]
版主，按照上面的方法，添加到无子级菜单下是可以，但是添加到同级菜单下有子级，之前正常的页面会报错，
runtime-core.esm-bundler.js:38 
       [Vue warn]: Component is missing template or render function. 
  at <ParentLayout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< null > key="/level/menu1/menu1-2" > 
  at <KeepAlive include= 
并页面空白。

![1](https://user-images.githubusercontent.com/45864590/196394442-2205fea1-5fe3-4935-943f-5f4238ad969f.png)

**Comment by wenlongFam** [comment]
添加子级的子级路由，页面打开是空白。

**Comment by wenlongFam** [comment]
版主，看一下这个 添加子级的子级路由，页面打开是空白的问题。

**Comment by wenlongFam** [comment]
解决了。
把添加菜单的父级的路由表里数据这样修改：component: null,//getParentLayout()
