### ISSUE TITLE
how to add token in header

### ISSUE THREAD

**Issue by myomyintaung1411** [kailong321200875/vue-element-plus-admin#171]
I have added to like these config.headers.token = token but it is not working

**Comment by kailong321200875** [comment]
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/32283845/194686183-23b32cfd-5138-40ef-be2d-7e53341b36dc.png">
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/32283845/194686193-a5ad21ae-a448-42a8-988a-721285ab7c2e.png">
