### ISSUE TITLE
前后端分离项目，后端的API接口有多个 怎么配置base_url

### ISSUE THREAD

**Issue by sunny1028** [kailong321200875/vue-element-plus-admin#189]
后端有多个api地址的host，
比如：
//登录请求
http://192.168.1.10/api/auth
//获取列表数据
http://192.168.2.10/api/data/list

我该如何在src\config\axios\config.ts配置文件中配置base_url.base？
页面上请求接口时我要怎么指定是哪个host？

**Comment by kailong321200875** [comment]
那可能得自己改造一下，可以把base变成一个对象，然后去存你不同的前缀

**Comment by sunny1028** [comment]
> 

感谢！
我正准备这么做。

**Comment by sunny1028** [comment]
> 那可能得自己改造一下，可以把base变成一个对象，然后去存你不同的前缀

感谢！
我正准备这么做。
