### ISSUE TITLE
怎么样增加外部封装好的组件

### ISSUE THREAD

**Issue by GzRichChen** [kailong321200875/vue-element-plus-admin#196]
需要一个组织架构图，在网上找了一下一个组件vue3-tree-org，这个要怎么样全局注册进来呢。
按照组件方的写法
import { createApp } from 'vue'
import vue3TreeOrg from 'vue3-tree-org';
import "vue3-tree-org/lib/vue3-tree-org.css";

const app = createApp(App)

app.use(vue3TreeOrg)
app.mount('#app')

**Comment by kailong321200875** [comment]
这个看下该组件的文档是怎么引入的，这已经跟项目本身没有多大关系了
