### ISSUE TITLE
table封装增强

### ISSUE THREAD

**Issue by zengzhihong** [kailong321200875/vue-element-plus-admin#2]
有一个很不错的table封装，建议可以做下参考
https://github.com/cool-team-official/cl-crud3

**Comment by kailong321200875** [comment]
> 有一个很不错的table封装，建议可以做下参考
> https://github.com/cool-team-official/cl-crud3

我看了下这个的表格，他只是做了表格上的扩展，并没有把功能都集成到表格组件里面去，我这个系统的表格组件，也是能自定义扩展的，原本的设想二次封装表格组件，满足element表格的所有属性和事件，然后可以由开发者自行去扩展，不太想干预太多逻辑。
