### ISSUE TITLE
作者你好，请问form怎么支持多级数据呢？我将table字段改为多级显示没问题，form不显示值了关联不到

### ISSUE THREAD

**Issue by Mystuddent** [kailong321200875/vue-element-plus-admin#207]

**Comment by kailong321200875** [comment]
什么意思，没看到，有例子吗

**Comment by Mystuddent** [comment]
![image](https://user-images.githubusercontent.com/24928560/202989145-f47cccc6-3bb8-4d34-a8c4-d89289cee9e2.png)
![1669015209821](https://user-images.githubusercontent.com/24928560/202989274-f890ff75-8559-431d-afcb-df94466530bd.jpg)

![1669015263214](https://user-images.githubusercontent.com/24928560/202988952-75821471-e396-4cd1-a9cb-1bf7da728aee.jpg)
我在form中将代码改为适配了两级属性，但是修改时没有保存table就变化了

**Comment by kailong321200875** [comment]
你应该是哪里数据双向绑定了，解绑一下或者深拷贝一下应该就能处理

**Comment by Mystuddent** [comment]
谢谢，我测试深拷贝后解决了。我之前只改动field和mock数据后，表格会不显示数据，因为key取不到数据，我在里面就加了一层判断分支，解决了form显示数据
