### ISSUE TITLE
作者你好，请问我在form里面增加了ElTree组件，怎么在Write组件里面拿到选择的数据？或者父组件怎么拿到Form里面的treeRef

### ISSUE THREAD

**Issue by Mystuddent** [kailong321200875/vue-element-plus-admin#209]
![image](https://user-images.githubusercontent.com/24928560/203494337-5147239b-b444-4173-8204-bea85de94f0d.png)

**Comment by kailong321200875** [comment]
跟传入属性一样，传入一个ref应该是可行的

**Comment by Mystuddent** [comment]
谢谢作者，我前几天已解决，传入需要的ref就可以了。
