### ISSUE TITLE
作者你好 这个是怎么把 text-[var(--top-header-text-color)] 编译成对应的css的

### ISSUE THREAD

**Issue by tpc-ht** [kailong321200875/vue-element-plus-admin#210]
![image](https://user-images.githubusercontent.com/59469126/204494509-08409001-dbad-4dbb-a8ee-f2daecca25c9.png)
作者你好。项目中添加这样的class `text-[var(--top-header-text-color)]`，自动编译成了
```
.text-[var(--top-header-text-color)]{
   color: var(--top-header-text-color)
}
```
这个是什么个原理/实现。有没有相关的文档？

**Comment by kailong321200875** [comment]
这个是windicss实现的，一个插件，你可以看一下
