### ISSUE TITLE
封装的Table，可以监听element-plus table原生组件的事件嘛？

### ISSUE THREAD

**Issue by 1391020381** [kailong321200875/vue-element-plus-admin#211]
我看源码，table属性是都可以传递给 element-plus table，但是事件看没有，可以直接监听嘛，但是源码看没有对应的处理？

**Comment by kailong321200875** [comment]
可以直接监听，支持element-plus table的所有事件，原先怎么写的现在就怎么写就可以

**Comment by 1391020381** [comment]
今天Vue3 文档 v-on 监听器继承 https://cn.vuejs.org/guide/components/attrs.html#v-on-listener-inheritance
应该是这样透传的吧。  vue2 只能通过 v-on="$listeners" 但是如果是 vue2 jsx 好像没有什么好的办法？
