### ISSUE TITLE
构建问题

### ISSUE THREAD

**Issue by pigW** [kailong321200875/vue-element-plus-admin#219]
构建过程异常的慢，暂时也没定位到原因，始终会卡几分钟。不一定是下图中的文件，每次构建总会卡几分钟，没有思路排查定位
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/20986922/208578913-d9097f21-4b46-4049-8ac9-936b5c5f583f.png">

系统信息：
  型号名称：	MacBook Pro
  型号标识符：	MacBookPro17,1
  型号：	Z11F000BPCH/A
  芯片：	Apple M1
  核总数：	8（4性能和4能效）
  内存：	16 GB

**Comment by xingyuv** [comment]
最新的pr 可以参考一下
![image](https://user-images.githubusercontent.com/41043753/208797715-4ec5b2da-a7ed-47c2-811d-3be2c0245386.png)

**Comment by xingyuv** [comment]
[#218](https://github.com/kailong321200875/vue-element-plus-admin/pull/218)

**Comment by kailong321200875** [comment]
请更新到最新版本
