### ISSUE TITLE
发布跨域问题

### ISSUE THREAD

**Issue by AbnerMai** [kailong321200875/vue-element-plus-admin#221]
发布之后访问nginx总是403跨域，配好的但还是不行：看了下应该是部署之后，发送请求时没有携带 content-type 这个请求头，奇怪，有大神部署成功的吗？求助:
![1672065416398](https://user-images.githubusercontent.com/26241803/209559493-71b77037-bd9d-49f6-bffa-425fb8bb4235.png)

nginx已经配置了支持跨域：
![73a1e55a95345459c158038319e7b34](https://user-images.githubusercontent.com/26241803/209559549-176d6f96-f778-4316-ba43-37b458f005b2.png)

**Comment by HelloYu** [comment]
403是权限不足的错误代码，你的CORS配置信息的不太对，用下面这个配置试试：
```
      if ($request_method = 'OPTIONS') {
        return 200;
      }
      add_header 'Access-Control-Allow-Origin '你的域名地址' always;
      add_header 'Access-Control-Allow-Credentials' 'false' always;  #如果使用JWT授权方式这里设置false，用cookies设置true
      add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range' always;
      add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH' always; #always告诉nginx错误代码403之类的也要加CORS头
```
