### ISSUE TITLE
Form Validator 使用问题

### ISSUE THREAD

**Issue by linshaoyong** [kailong321200875/vue-element-plus-admin#229]
demo 中只有 required 的使用例子
其实 hooks/web/useValidator.ts  里有多个校验函数 required/lengthRange/notSpace/notSpecialCharacters/isEqual

像密码是否相等的校验，在 element-plus 能找到相应的[例子](https://element-plus.org/zh-CN/component/form.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%A1%E9%AA%8C%E8%A7%84%E5%88%99)

刚接触前端，不太会用封装后的 Form 自定义校验，望指导

**Comment by kailong321200875** [comment]
https://github.com/kailong321200875/vue-element-plus-admin/blob/node-admin/src/views/Login/components/RegisterForm.vue 可以参考下这个
