### ISSUE TITLE
你这个限制太多了

### ISSUE THREAD

**Issue by rehtafuoy** [kailong321200875/vue-element-plus-admin#230]
你这个限制太多了，通用性不行。还必须用pnpm进行install，难怪用的人比vue-element-admin少那么多。用npm install都报错，如果连基础的方式都不能支持的话，劝你还是别做了

**Comment by kailong321200875** [comment]
你这话说的就很没意思 开源又不强制您用 您也别瞎操心那么多 自己搞一个？OK?

**Comment by rehtafuoy** [comment]
> 你这话说的就很没意思 开源又不强制您用 您也别瞎操心那么多 自己搞一个？OK?

拿vue-element-admin换个皮肤加点东西而已，有本事你别用element自己做个完全不一样的，抄袭别人的还好像自己多厉害一样

**Comment by kailong321200875** [comment]
> > 你这话说的就很没意思 开源又不强制您用 您也别瞎操心那么多 自己搞一个？OK?
> 
> 拿vue-element-admin换个皮肤加点东西而已，有本事你别用element自己做个完全不一样的，抄袭别人的还好像自己多厉害一样

不好意思哈 我行你不行 您不会只会口嗨吧

**Comment by rehtafuoy** [comment]
> 吧

你行你写啊，我等着看你写个不用elementui的ui框架呢，哈哈哈

**Comment by kailong321200875** [comment]
> > 吧
> 
> 你行你写啊，我等着看你写个不用elementui的ui框架呢，哈哈哈

您真的好搞笑。。好好赚钱吧，人菜瘾大？

**Comment by rehtafuoy** [comment]
> > > 吧
> > 
> > 
> > 你行你写啊，我等着看你写个不用elementui的ui框架呢，哈哈哈
> 
> 您真的好搞笑。。好好赚钱吧，人菜瘾大？

呦呵，写不了就直接承认，抄袭复制粘贴改一改的渣渣，在这装大神，可笑

**Comment by songyazhao** [comment]
这个人挺有意思，看他账号貌似是头几天刚创建的，应该是刚入行不久的小白，作者不用理他。

**Comment by fero2004** [comment]
lz你小脑不正常？限制多自己写呗，没人逼你用？你写不出来老实把屁股撅着
