### ISSUE TITLE
InputNumber 如何设置 controls-position 属性

### ISSUE THREAD

**Issue by BackMountainDevil** [kailong321200875/vue-element-plus-admin#231]
在 [element-plus文档](https://element-plus.gitee.io/zh-CN/component/input-number.html#%E6%8C%89%E9%92%AE%E4%BD%8D%E7%BD%AE)中有说可以设置  controls-position 属性 使得两个调节玩意都在右边。

```bash
  {
    field: 'runTime',
    label: t('exampleDemo.runTime'),
    component: 'InputNumber',
    value: 0,
    formItemProps: {
      rules: [required()]
    }
  }
```

element-plus文档的案例直接复制过来没法跑

```bash
  <el-input-number
    v-model="num"
    :min="1"
    :max="10"
    controls-position="right"
    size="large"
    @change="handleChange"
  />
```

**Comment by kailong321200875** [comment]
这样就可以了 @BackMountainDevil 
{
    field: 'runTime',
    label: t('exampleDemo.runTime'),
    component: 'InputNumber',
    value: 0,
    formItemProps: {
      rules: [required()]
    },
    componentProps: {  controlsPosition: 'right'  }
  }

**Comment by BackMountainDevil** [comment]
不愧是2006年的《时代周刊》年度人物，感恩的心
