### ISSUE TITLE
这个项目没有明白base,dev,pro的接口ip从哪里设置呀？必须从config.ts的"api请求基础路径"那里设置吗？

### ISSUE THREAD

**Issue by chunten** [kailong321200875/vue-element-plus-admin#232]
这个项目没有明白base,dev,pro的接口ip从哪里设置呀？必须从config.ts的"api请求基础路径"那里设置吗？

**Comment by chunten** [comment]
好像必须从这里设置，但是.env.base这些文件里的VITE_API_BASEPATH=base好像就没有什么意义 了。。
const config: {
  base_url: {
    base: string
    dev: string
    pro: string
    test: string
  }
  result_code: number | string
  default_headers: AxiosHeaders
  request_timeout: number
} = {
  /**
   * api请求基础路径
   */
  base_url: {
    // 开发环境接口前缀
    base: '',

    // 打包开发环境接口前缀
    dev: '',

    // 打包生产环境接口前缀
    pro: 'http://192.168.1.201:8888/',

    // 打包测试环境接口前缀
    test: '',

  },

  /**
   * 接口成功返回状态码
   */
  result_code:0,

  /**
   * 接口请求超时时间
   */
  request_timeout: 60000,

  /**
   * 默认接口请求类型
   * 可选值：application/x-www-form-urlencoded multipart/form-data
   */
  default_headers: 'application/json'
}
export { config}

**Comment by kailong321200875** [comment]
VITE_API_BASEPATH 只是用于区分取哪个环境的接口前缀，真正要写的接口地址就是config.ts里面对应各种环境的接口前缀，比如你正式环境的接口是 http://192.168.1.201:8888/xxxxx/xxx/xx 那你在pro 中就可以填写 http://192.168.1.201:8888/ 其他dev test 同理，base 是开发环境上用的，就是我们启动项目的时候用的
