### ISSUE TITLE
所有页面不能触发onActivated事件

### ISSUE THREAD

**Issue by chunten** [kailong321200875/vue-element-plus-admin#233]
我对照你的源项目文件，onActivated确实能触发，但我不知道动住哪里了，所有页面的onActivated不能触发，我把菜单返回数据中的noCache去掉(没有不是就是false)也不行，有大神知道可能是哪里的问题不？

**Comment by kailong321200875** [comment]
name 是不是没匹配上，name需要保持一致才能进行缓存 这个还不太好排查是哪里的问题
