### ISSUE TITLE
第三种布局，弹框以后最右边出现空白

### ISSUE THREAD

**Issue by kyo3223** [kailong321200875/vue-element-plus-admin#235]
复现步骤：
1.切换到第三种布局（菜单置顶那种）
2.按f5刷新页面
3.弹框，或者抽屉
现象：
最右边出现留白。boby属性少了17px。
`<body class="el-popup-parent--hidden" style="width: calc(100% - 17px);">`

**Comment by kailong321200875** [comment]
已处理
