### ISSUE TITLE
commit 时request拦截器 config: AxiosRequestConfig 校验报错

### ISSUE THREAD

**Issue by kailiu999** [kailong321200875/vue-element-plus-admin#236]
![image](https://user-images.githubusercontent.com/43026300/219248278-d9779b50-4dfc-4ed1-b347-f27ecc51c5dc.png)
![image](https://user-images.githubusercontent.com/43026300/219248420-a6931be4-80c4-4362-9f8a-a1aa725d3ee3.png)
这是为啥？？？

**Comment by yaru-w** [comment]
+1，也遇到这个问题了，目前还没解决

**Comment by kailiu999** [comment]
> +1，也遇到这个问题了，目前还没解决

![image](https://user-images.githubusercontent.com/43026300/220304382-608edee7-84b4-4bfc-b5ee-a1b8b01b739a.png)
把提交检测注释掉，不管它了。

**Comment by kailong321200875** [comment]
已处理
