### ISSUE TITLE
如何在Descriptions.vue中使用获取表单数据(getFormData)?

### ISSUE THREAD

**Issue by zhengtong0898** [kailong321200875/vue-element-plus-admin#249]
在[这里](https://github.com/kailong321200875/vue-element-plus-admin/blob/master/src/views/Components/Descriptions.vue#L70)加入几行代码，发现无法获取到表单数据.
```
type formType = {
  username: string
  nickName: string
  phone: string
  email: string
  addr: string
}

const formValidation = () => {
  unref(elFormRef)!.validate( async (isValid) => {
    console.log(isValid)

    console.log('postForm: ', isValid)
    const { getFormData } = methods
    const formData = await getFormData<formType>()
    console.log('formData: ', formData)
  })
}
```

![image](https://user-images.githubusercontent.com/17564324/225850840-dd8728aa-dd69-4320-a86d-6a94a72f8707.png)

有人知道怎么解吗?

**Comment by kailong321200875** [comment]
@zhengtong0898 
<img width="898" alt="image" src="https://user-images.githubusercontent.com/32283845/225852151-ae16f84f-b36b-4fa2-9461-363ff047e88f.png">
这里不就可以拿到表单数据了吗

**Comment by zhengtong0898** [comment]
感谢回复这么迅速 @kailong321200875 

好的，这样也可以拿到数据。

但是我很奇怪为啥getFormData无法拿到数据，但是login页面的表单缺可以拿到。
因为我看到login页面时通过getFormData获取到数据，然后提交网络请求的。

这里面有特别的注意事项吗?

**Comment by kailong321200875** [comment]
@zhengtong0898 使用场景不一样，因为表单要嵌入到描述组件里面，所以需要自定义，只能传入model来绑定数据
