### ISSUE TITLE
【大版本重构计划】

### ISSUE THREAD

**Issue by kailong321200875** [kailong321200875/vue-element-plus-admin#262]
- [x] windcss替换为unocss
- [x] 布局细节调整
- [x] Form组件重构
- [x] Table组件重构
- [x] 代码可读性优化
- [x] axios二次封装重构
- [x] 相同标签页支持不同参数多开
- [x] 部门管理及角色管理示例
- [x] 重新开放template分支
- [x] 添加锁定屏幕功能
- [x] 详情组件重构
- [x] 查询组件重构

**Comment by vela666** [comment]
为啥顶部菜单布局的时候  浏览器宽度缩小的一定程度 就自动改成 左侧布局了。。。

**Comment by kailong321200875** [comment]
> 

因为其他布局并不适合移动端的

**Comment by kailong321200875** [comment]
> 因为其他布局并不适合移动端的

因为其他布局并不适合移动端的

**Comment by notlaughingzzm** [comment]
可以借鉴一下vben的部分api，拓展性还是差了些，包括search，dialog这些

**Comment by sanhaowuai** [comment]
> * 组件重构

示例中没有树形表格展示，这个功能挺常用的，父子嵌套展示，希望大佬这次升级能加入树形表格的展示示例

**Comment by tengfei666666** [comment]
加一个上传组件

**Comment by brucewuu520** [comment]
重构版大概什么时间发布呀？好期待

**Comment by kailong321200875** [comment]
> 重构版大概什么时间发布呀？好期待

时间不敢保证 只能说想自己想法是六月底

**Comment by zj874** [comment]
请问我想把master的windicss替换成unocss，可以直接替换吗，需要做哪些排查

**Comment by hzzdong** [comment]
期待~~~

**Comment by kailong321200875** [comment]
> 请问我想把master的windicss替换成unocss，可以直接替换吗，需要做哪些排查

你可以参考下v2版本的。。我记得还是要改一点东西的

**Comment by kailong321200875** [comment]
> 重构版大概什么时间发布呀？好期待

会尽快的。。最近太忙了，已经很努力的在赶了

**Comment by more-strive** [comment]
可以集合在线编辑
https://github.com/more-strive/vue-fabric-draw

**Comment by neozo** [comment]
为什么现在都喜欢用windcss、unocss ，特别是团队开发，维护起来头疼啊🤔️

**Comment by kailong321200875** [comment]
> 为什么现在都喜欢用windcss、unocss ，特别是团队开发，维护起来头疼啊🤔️

用习惯了也还好，所见即所得，也不必要为了取类名而烦恼了
