### ISSUE TITLE
 yarn  build:pro yarn run 打包的时候报错

### ISSUE THREAD

**Issue by ruanlp** [kailong321200875/vue-element-plus-admin#269]
$ vite build --mode pro Building [████████████████████████░░░░░░░░░░░░░░░░] 61% | Time: 14.1s Build failed. Please check the error message    ERROR  error during build:                                                                                                11:34:33 SyntaxError: At least one <template> or <script> is required in a single file component.     at Object.parse$4 [as parse] (D:\workspace\node_modules\@vue\compiler-sfc\dist\compiler-sfc.cjs.js:5269:21)

**Comment by ruanlp** [comment]
解决

**Comment by ruanlp** [comment]
解决

**Comment by dongxingrui** [comment]
您好  能说下怎么解决的嘛？
