### ISSUE TITLE
请问您这边有比较详细的部署教程吗

### ISSUE THREAD

**Issue by 18162305875** [kailong321200875/vue-element-plus-admin#272]
本人小白一个，最近想自己做一个小系统，然后用了您的这个框架。然后按照文档进行打包和部署。发现无法打开。但是打包之后通过预览命令是可以打开的。。所以我想请教一下您。这是怎么回事，然后该怎么处理。望大佬解答

**Comment by kailong321200875** [comment]
<img width="792" alt="image" src="https://user-images.githubusercontent.com/32283845/236976937-6ee36dde-99e7-42c9-8048-ec7aedef3510.png">

修改一下打包路径应该就可以了，估计你部署的地址有多余的路径，需要把路径给加上去才行
