### ISSUE TITLE
样式+图片上传

### ISSUE THREAD

**Issue by dreamLXD** [kailong321200875/vue-element-plus-admin#278]
table里面 h函数放入 elimage 有样式问题。我强行样式覆盖了。能看一下是element的bug还是 组件的bug吗、form表单 组件中可以放入图片上传和预览功能吗？这个也是经常会用到的。

**Comment by hzzdong** [comment]
确实，Upload组件确实非常重要，不知道什么时候能封装？

**Comment by kailong321200875** [comment]
form例子已经集成了upload，可以自行查看

**Comment by hzzdong** [comment]
> form例子已经集成了upload，可以自行查看

好的，感谢！
