### ISSUE TITLE
在form组件里，setValues后，不会触发onChange事件

### ISSUE THREAD

**Issue by YcZzy** [kailong321200875/vue-element-plus-admin#281]
const schema = reactive<FormSchema[]>([
{
    field: 'field',
    label: 'checkbox',
    component: 'Checkbox',
    value: [],
    componentProps: {
      options:[{value:'checkbox',label:'checkbox'}]
      onChange: (val: any) => {
      }
    }
  }
])

setValues({
field:['checkbox']
})

**Comment by LuckyArdhika** [comment]
jjk

**Comment by kailong321200875** [comment]
具体可以查看 https://github.com/element-plus/element-plus/issues/14583，目前表现形式是合理的
