### ISSUE TITLE
使用了ElementAdmin 部分使用了封装的插件 部分页面没有使用插件，切换页面时资源加载特别慢 

### ISSUE THREAD

**Issue by 1939823447** [kailong321200875/vue-element-plus-admin#284]
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/56708168/ecd72454-6881-4980-98d9-da1a56e4ef10)
每次切换页面都会重新加载这些资源文件 导致页面加载缓慢  请问有什么办法优化吗 谢谢大佬帮我解答一下

**Comment by kailong321200875** [comment]
已对开发环境进行了优化
