### ISSUE TITLE
UseForm添加Button问题

### ISSUE THREAD

**Issue by im-here** [kailong321200875/vue-element-plus-admin#287]
我想在UseForm添加Button
在componentMap.ts和components.d.ts都分别添加的对应的Button组件，在使用的时候能也引入进来，但是问题就是引入进来的button没有文字，这个怎么解决呢？

**Comment by mynetfan** [comment]
https://element-plus-admin-doc.cn/components/form.html#componentprops

使用default插槽

**Comment by bobohuochai** [comment]
参考登录页，其实不用加Button 组件。
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/22309079/ede8da45-c590-450e-9747-97835b38a60e)

**Comment by im-here** [comment]
@bobohuochai 感谢！
