### ISSUE TITLE
请问部分接口用了mock，部分用了线上接口，本地测试线上接口时看不到网络里的请求响应，怎么解决呢

### ISSUE THREAD

**Issue by Don0429** [kailong321200875/vue-element-plus-admin#288]
请问部分接口用了mock，部分用了线上接口，本地测试线上接口时看不到网络里的请求响应，怎么解决呢 
@huanghong1125

**Comment by hzzdong** [comment]
vite.config.ts文件中server proxy中配置你线上接口的规则吧

**Comment by Don0429** [comment]
感谢，已经解决
&nbsp;


Bonjour
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月28日(星期一) 下午4:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [kailong321200875/vue-element-plus-admin] 请问部分接口用了mock，部分用了线上接口，本地测试线上接口时看不到网络里的请求响应，怎么解决呢 (Issue #288)





 
vite.config.ts文件中server proxy中配置你线上接口的规则吧
