### ISSUE TITLE
使用vue-element-plus-admin-template这个版本，build:pro打包会报错

### ISSUE THREAD

**Issue by seasonl2014** [kailong321200875/vue-element-plus-admin#3]
E:\anzhuang\nodejs\node.exe E:\anzhuang\nodejs\node_global\node_modules\yarn\bin\yarn.js run build:pro
yarn run v1.22.10
$ vue-cli-service build

✔  Building for production...
 ERROR  ReferenceError: entryPages is not defined
ReferenceError: entryPages is not defined

**Comment by kailong321200875** [comment]
> E:\anzhuang\nodejs\node.exe E:\anzhuang\nodejs\node_global\node_modules\yarn\bin\yarn.js run build:pro
> yarn run v1.22.10
> $ vue-cli-service build
> 
> ✔ Building for production...
> ERROR ReferenceError: entryPages is not defined
> ReferenceError: entryPages is not defined

已处理
