### ISSUE TITLE
Form rule 添加email校验规则时报错

### ISSUE THREAD

**Issue by husiwei-github** [kailong321200875/vue-element-plus-admin#315]
const rules = reactive({
  email: [
    required(),
    {
      type: 'email',
      message: '请输入正确的邮箱地址',
      trigger: ['blur', 'change']
    }
  ]
})

<Form :rules="rules" @register="formRegister" :schema="formSchema" />

不能将类型“{ email: ({ required: boolean; message: string; } | { type: string; message: string; trigger: string[]; })[]; }”分配给类型“Partial<Record<string, Arrayable<FormItemRule>>>”。
  属性“email”与索引签名不兼容。ts(2322)

麻烦帮看下是什么问题

**Comment by kailong321200875** [comment]
import { FormItemRule } from 'element-plus'  
const rules = reactive<{
  [key: string]: FormItemRule[]
}>

@husiwei-github 试一下这样

**Comment by husiwei-github** [comment]
已解决，3Q
