### ISSUE TITLE
两个密码一致性验证问题

### ISSUE THREAD

**Issue by husiwei-github** [kailong321200875/vue-element-plus-admin#320]
const equalToPassword = (): FormItemRule => {
  return {
    asyncValidator: async (_, val, callback) => {
      const data = await getFormData()
      if (data?.newPassword !== val) {
        callback(new Error('两次输入的密码不一致'))
      } else {
        callback()
      }
    }
  }
}
分配给类型“Partial<Record<string, Arrayable<FormItemRule>>>”。
  属性“confirmPassword”与索引签名不兼容。ts(2322)

大神帮看下

**Comment by kailong321200875** [comment]
这样子看不出什么问题 需要提供更具体的代码

**Comment by husiwei-github** [comment]
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/53715663/2d04cfa3-a496-45ec-bc7d-a62f736d46f3)

**Comment by kailong321200875** [comment]
@husiwei-github 给rules加个类型{
[key:string]:FormItemRule[]
}
