### ISSUE TITLE
关于表格工具栏的封装

### ISSUE THREAD

**Issue by vvandk** [kailong321200875/vue-element-plus-admin#329]
我看了当前表格工具栏的组件，发现列设置功能为注释的，并且我打开注释后发现其并没有写完，请问这个功能之后会完善起来吗？

目前我最大的问题是，当我启用表格工具栏功能后，会在表格的上右方展示，如果我需要在上左方添加新增按钮应该如何添加，让他们对齐在一行，能否给一个示例，我在当前的在线系统中没有看到关于这个的示例

![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/108704266/1e6c84ab-42ff-434b-92ac-9c796256ad1d)

**Comment by vvandk** [comment]
启用表格工具栏时，如何让按钮与工具栏对齐在一行？

![18620f6ca05a88a109c70f14aa40d9b](https://github.com/kailong321200875/vue-element-plus-admin/assets/108704266/6cb13670-ba8e-478a-9de8-dacdc96ea6fb)

**Comment by kailong321200875** [comment]
自己加一个组件里面加个插槽就行了，列设置功能后续会加 目前还没写好
