### ISSUE TITLE
关于表格工具栏

### ISSUE THREAD

**Issue by vvandk** [kailong321200875/vue-element-plus-admin#330]
关于表格工具栏部分，我已经将按钮与工具栏部分的插槽加好了，列设置功能部分我看了比较复杂，想请问一下列设置功能是否有安排进行程，大概啥时候能更新上呢

按钮与工具栏部分的插槽代码：
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/108704266/a3f06332-aae7-4ba4-9f3b-6dd3159bacdb)

**Comment by kailong321200875** [comment]
最近没啥时间去写 时间不太确定
