### ISSUE TITLE
dialog 中展示 Descriptions 问题

### ISSUE THREAD

**Issue by vvandk** [kailong321200875/vue-element-plus-admin#331]
在 1.x 版本中 dialog 中展示 Descriptions ，当value过长时会自动换行

![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/108704266/2ebe053f-27c3-4c1b-969f-2e38fed596b5)

但在新版本中 dialog 中展示 Descriptions ，当value过长时会不会自动换行

![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/108704266/f59cd13f-3c10-49d6-bf67-0f77bb6a44f4)

请问这个问题应该怎么解决

**Comment by ma6566966** [comment]
怎么解决的啊？
