### ISSUE TITLE
表单下拉框使用optionApi时默认值选中问题

### ISSUE THREAD

**Issue by ywu2014** [kailong321200875/vue-element-plus-admin#333]
【场景描述】
通过路由跳转到如下页面
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/6658901/70c9b5e0-43db-4d11-a02c-96aff3e0f157)
页面中的查询条件部分设置了默认值，第一个查询条件是下拉框，下拉框中的选项是通过后端接口获取的；下拉框选中的值从路由参数中获取，schema如下（使用了optionApi和value属性）

```
const crudSchemas = reactive<CrudSchema[]>([
  ...
  {
    field: 'dictId',
    label: '字典名称',
    search: {
      component: 'Select',
      componentProps: {
        options: [],
        props: {
          label: 'name',
          value: 'id',
          key: 'id'
        }
      },
      value: query.dictId,
      optionApi: async () => {
        console.log('optionApi 调用开始')
        const res = await getDictListApi({ pageIndex: 1, pageSize: 10 })
        console.log('optionApi 调用结束')
        return res.data.items
      }
    }
  }
])
```

问题是页面渲染完后下拉框显示的是选项的value，而不是选项的label，即正常应该是这样才对
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/6658901/ff438218-ded6-419f-9a6c-b778285ab702)

这个问题该怎么解决？

**Comment by kailong321200875** [comment]
异步的出现这种问题不是很正常吗，可以等到加载完options的时候在去赋值
