### ISSUE TITLE
更换主题色后，组件hover或者disable状态的颜色不匹配，是否考虑优化一下

### ISSUE THREAD

**Issue by congeemei** [kailong321200875/vue-element-plus-admin#336]
![gif](https://github.com/kailong321200875/vue-element-plus-admin/assets/130620386/357c9a85-826e-4da4-bb1a-5a7ffb12f3be)

**Comment by kailong321200875** [comment]
element-plus的问题，需要找个解决方案来实现按钮的动态主题，而不是传入一个color属性

**Comment by kailong321200875** [comment]
已支持
