### ISSUE TITLE
TableColumn 怎么在组件插槽问题

### ISSUE THREAD

**Issue by zhupanpanya** [kailong321200875/vue-element-plus-admin#337]
TableColumn 怎么在组件中写插槽进去呀，按照例子，是否只能使用tsx

![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/33818173/c4846151-69de-435f-bea1-812dd73785a9)

**Comment by kailong321200875** [comment]
目前只支持tsx，暂时没有支持template的打算
