### ISSUE TITLE
能否新增卡片列表

### ISSUE THREAD

**Issue by CC-Cheunggg** [kailong321200875/vue-element-plus-admin#344]
能否新增卡片列表，就跟阿里的卡片列表一样

**Comment by kailong321200875** [comment]
@RPCheung 需要给个参考地址

**Comment by CC-Cheunggg** [comment]
> @RPCheung 需要给个参考地址
https://preview.pro.ant.design/list/card-list/
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/18390076/a6457114-fc4b-4c7e-9b98-bfcab9136529)

https://preview.pro.ant.design/account/center/
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/18390076/50b9c135-3ebf-4f8e-8665-b214a78b2a19)

感谢
