### ISSUE TITLE
mini 版本登录失败

### ISSUE THREAD

**Issue by sunnyguohua** [kailong321200875/vue-element-plus-admin#351]
# 版本信息
PS D:\approot\vue-element-plus-admin> git branch -v
  master d543e56 feat: Waterfall
* mini   fbe68ba fix: 修复BUG

PS D:\approot\vue-element-plus-admin> node -v
v16.20.2
PS D:\approot\vue-element-plus-admin> pnpm -v
8.8.0
PS D:\approot\vue-element-plus-admin> npm -v
8.19.4

# 错误信息
index.ts:138 [Vue Router warn]: No match found for location with path "/level"

![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/6479673/23fa545c-ff03-4a91-88e4-3ca96ebf499c)

**Comment by alwaysIn-lilijie** [comment]
<img width="971" alt="image" src="https://github.com/kailong321200875/vue-element-plus-admin/assets/50645844/57625d79-586e-4c20-bf7c-a1463db258f2">

**Comment by kailong321200875** [comment]
已修复
