### ISSUE TITLE
MIni installation reported an error as follows：（Error: Unknown variable dynamic import: ../../locales/[object Object].ts）

### ISSUE THREAD

**Issue by fredGmm** [kailong321200875/vue-element-plus-admin#352]
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/24388938/4a9cd99a-8e38-4664-b51e-af196d93448a)

**Comment by wuxiutong** [comment]
你修改下浏览器的本地缓存的中的lang值修改为zh-CN或en即可。
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/16028422/c8abd220-1111-4e09-a2eb-3536a78d6976)
