### ISSUE TITLE
求救，无法使用 element-plus/icons-vue 无法集成其他组件，只要这个组件使用了element-plus/icons-vue

### ISSUE THREAD

**Issue by XiaoJia12138** [kailong321200875/vue-element-plus-admin#357]
想要集成 vform，但是vform需要引入 element-plus/icons-vue，
本项目引入 element-plus/icons-vue后，就无法打包了，可以运行。打包就报异常。应该是循环引用或依赖之类的。
可以 引入 element-plus/icons-vue后，随便组成 一个图片，然后试试打包。没法通过。

**Comment by XiaoJia12138** [comment]
全局导入 element-plus  也会导致 打包不了。

**Comment by SsnAgo** [comment]
@XiaoJia12138 无法全局引入icons-vue的问题解决了吗  我也遇到这个问题  目前只能在对应文件手动引入

**Comment by XiaoJia12138** [comment]
> @XiaoJia12138 无法全局引入icons-vue的问题解决了吗 我也遇到这个问题 目前只能在对应文件手动引入

vite.config.ts文件 将这个属性改下  sourcemap: false, 就可以了。

**Comment by SsnAgo** [comment]
> vite.config.ts文件 将这个属性改下 sourcemap: false, 就可以了。

好的 感谢~
