### ISSUE TITLE
如何在同一个表单Form分成上下两部分，中间添加别的组件？

### ISSUE THREAD

**Issue by SsnAgo** [kailong321200875/vue-element-plus-admin#359]
比如有个 上、中、下的页面结构。上、下是属于同一个表单的数据。中间可以是任意一个别的组件，比如一张图片。
用提供的数据驱动的方式能够实现吗？

**Comment by kailong321200875** [comment]
不是可以使用插槽的方式吗，原理跟你自定义其他表单项不是一个样吗，formItemProps有提供slots
