### ISSUE TITLE
i18n-ally 没有效果 提示：i18n-ally-key-missing

### ISSUE THREAD

**Issue by chenyRain** [kailong321200875/vue-element-plus-admin#362]
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/24472819/94cdcfbc-a19d-4cca-b377-1689fe60a941)

实际是能正常显示，但是vscode始终报这个不存在，这个怎么解决

**Comment by herohql** [comment]
都有这个问题

**Comment by kailong321200875** [comment]
不必理会
