### ISSUE TITLE
Message 多次调用只能弹出来第一个，你们到底改了什么，别人家的都是正常的

### ISSUE THREAD

**Issue by xnng** [kailong321200875/vue-element-plus-admin#366]

**Comment by 871850262** [comment]
解决了吗

**Comment by gwoose** [comment]
解决了么, 怎么调整好了么?

**Comment by xnng** [comment]
这个问题是 `src/components/ConfigGlobal/src/ConfigGlobal.vue` 里的这一行导致的：

```vue
:message="{ max: 1 }"
```

如果想恢复 Element Plus 的默认行为，直接把这行删掉即可。删掉后多次调用 `ElMessage.xxx()` 会按 Element Plus 默认逻辑正常展示多条 Message。

另外说一下我对这个设计的理解：现在这个配置的实际效果是“永远只显示第一个”，第一个 Message 没关闭时，后面的 Message 会被直接丢掉。但从真实使用场景看，如果业务想限制最多只显示一条，通常更符合预期的行为应该是“永远显示最后一个”，也就是新 Message 覆盖旧 Message。

不过 Element Plus 当前的 `message.max` 语义不是覆盖，而是达到上限后忽略新消息。要实现“只保留最后一个”，需要项目自己封装一层 Message 调用，比如每次弹出前先关闭旧 Message，再弹新的；如果要全项目统一替换，改动会比直接删除这行大一些。所以最低成本的解决方式就是删掉这行配置。
