### ISSUE TITLE
在axios中使用router跳转报错

### ISSUE THREAD

**Issue by jiaicon** [kailong321200875/vue-element-plus-admin#367]
我在config/axios/config.ts中配置响应拦截器，使用router跳转，pnpm dev启动时报大量错误，下面截图是我更改的代码
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/34124517/fc9f1abb-0caa-485b-b339-89fb7e55c7fd)
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/34124517/088c44d7-2a8b-4dbd-be0a-8ba52b397476)
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/34124517/62ad9eb4-abbc-4868-baea-f7f9b9320abc)

**Comment by caicf** [comment]
可以再store里或者封装到util里处理

**Comment by jiaicon** [comment]
> 可以再store里或者封装到util里处理

也不行，只要调用了router控制台就会出现错误，这个是什么原因造成的？刚用Vue没多久，希望能解答下。

**Comment by kailong321200875** [comment]
是会有这种问题，目前不懂是因为什么引起的，有待排查

**Comment by kailong321200875** [comment]
> > 可以再store里或者封装到util里处理
> 
> 也不行，只要调用了router控制台就会出现错误，这个是什么原因造成的？刚用Vue没多久，希望能解答下。

初步判定，是因为mock插件引起的，如果项目中已经不需要用到mock了，可以把相关代码和文件删除掉看看 @jiaicon

**Comment by jiaicon** [comment]
> > > 可以再store里或者封装到util里处理
> > 
> > 
> > 也不行，只要调用了router控制台就会出现错误，这个是什么原因造成的？刚用Vue没多久，希望能解答下。
> 
> 初步判定，是因为mock插件引起的，如果项目中已经不需要用到mock了，可以把相关代码和文件删除掉看看 @jiaicon

好的，去掉确实不报错了
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/34124517/d7df2da0-aefd-4cb2-a111-b945be7c5d25)
