### ISSUE TITLE
在那里切换后端路由？

### ISSUE THREAD

**Issue by CrazyCat6** [kailong321200875/vue-element-plus-admin#368]
在那里切换后端路由？

**Comment by CrazyCat6** [comment]
![1](https://github.com/kailong321200875/vue-element-plus-admin/assets/38643408/3f315476-13a7-46e9-a12a-8ff8f59545ce)
在哪里设置的dynamicRouter和serverDynamicRouter的值？

**Comment by kailong321200875** [comment]
直接改成你想要的就行了
