### ISSUE TITLE
关于封装的Axios调用实际的开发后台 res提示undefine无法获得返回结果，非常感谢。

### ISSUE THREAD

**Issue by tanpengch** [kailong321200875/vue-element-plus-admin#378]
各位大神，我搭建了这个框架学习中，mock数据没问题，我修改了VITE_API_BASE_PATH为实际的服务地址。并且export const loginApi = (data: TransRequest): Promise<IResponse<TransResponse>> => {
  return request.post({ url: '/CoreService.svc/CoreService', data })
}
对于传入响应interface都进行了修改。后天可以接受请求，但是返回的res提示undefine,不知道哪里还需要配置。export interface export interface TransResponse {
  ResponseCode: string
  ResponseInfo: string
  ResponseBody: string
  ResponseDateTime: string

  ReturnCode: string
  ReturnMsg: string
  ReturnBody: string

  //交易继续执行类型 当前主要用于区分北京/异地患者
  ResponseType: string

  /// <summary>
  /// 结果总数据量 为翻页
  /// </summary>
  ResultCount: number

  /// <summary>
  /// 交易类型
  /// </summary>
  /// 需要回填回去
  action: string

  /// <summary>
  /// 交易返回参数1-5
  /// </summary>
  /// 20231112
  param1: string
  param2: string
  param3: string
  param4: string
  param5: string
}
export interface TransRequest {
  // 	"AppID":"800",
  // "AppVersion":"5.0",
  // "TimeStamp":"2019-01-01",
  // "TransBody":"021510010120231115212915101376" ,
  //   "TransBody1":"reg",
  // "TransID":"sendToPacsEx",
  // "TransLogID":"1000000"
  AppID: string
  AppVersion: string
  TransLogID: string
  TimeStamp: string
  TransID: string
  TransBody: string
  TransBody1: string
}
这个函数
const service = {
  request: (config: RequestConfig) => {
    return new Promise((resolve, reject) => {
      if (config.interceptors?.requestInterceptors) {
        config = config.interceptors.requestInterceptors(config as any)
      }
      axiosInstance
        .request(config)
        .then((res) => {
          **console.log('res=' + res)**
          resolve(res)
        })
        .catch((err: any) => {
          console.log('request err' + err)
          reject(err)
        })
    })
  },

**Comment by kailong321200875** [comment]
<img width="1425" alt="image" src="https://github.com/kailong321200875/vue-element-plus-admin/assets/32283845/71e96d3d-bf8c-4805-aff3-4af8a0d11a34">
这这里去修改，看下code是否和SUCCESS_CODE字段一致

**Comment by tanpengch** [comment]
收到，我查了下，核心交易写法不同，没有code这个返回值，这个地方我改为if (response.status === config.code) {
    return response.data  就是=200就返回了，老师，您封装的很严密，所以这个地方报文不同就没法使用了，另外不是成功吗直接就logout这个是业务逻辑方面的要求？
