### ISSUE TITLE
mini分支下缓存app失效

### ISSUE THREAD

**Issue by tidycode** [kailong321200875/vue-element-plus-admin#390]
拉取了mini最新分支，安装运行后，发现app并没有存储到localstorage
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/5961374/a77429fa-c384-471b-9129-1be32953b73a)
由截图可以看到，localstorage有两个item：user和permission，这两个是对应store/module下各自文件，是正确的。
然而，store/module下的app并没有存储，导致了设置项目配置相关属性，刷新页面后，配置数据全都丢失了

node 版本 v18.0.0
pnpm 版本 8.9.2

**Comment by tidycode** [comment]
补充：在上一个版本中是正常的。上一个版本中的app.ts中，使用的的是
import { useStorage } from '@/hooks/web/useStorage'
const { getStorage, setStorage } = useStorage()
直接操作localstorage，而现在最新的mini分支中，使用的是
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'
怀疑和这个新的插件有关系，但很奇怪的是，user和permission也是通过pinia-plugin-persistedstate存储，是正常的，但是app就是一直不行

**Comment by kailong321200875** [comment]
已处理
