### ISSUE TITLE
文档中去掉mock的方法与实际代码不符

### ISSUE THREAD

**Issue by PandaJu** [kailong321200875/vue-element-plus-admin#391]
[根据文档](https://element-plus-admin-doc.cn/guide/mock.html#%E6%8E%A5%E5%8F%A3%E6%9C%89%E4%BA%86%EF%BC%8C%E5%A6%82%E4%BD%95%E5%8E%BB%E6%8E%89-mock)

> 接口有了，如何去掉 mock
可以在vite.config.ts中删除 MockDevServerPlugin 对应的代码。

但是目前在vite.config.ts文件中，没有 MockDevServerPlugin 代码

另外，在`src/api`中，所有的url都是`/mock`开头的，这样不太符合规则吧？

**Comment by kailong321200875** [comment]
文档错误已处理，以/mock开头，只是一个示例而已，真实的还需要根据业务自己修改。
