### ISSUE TITLE
能否出一款layout默认为top的布局

### ISSUE THREAD

**Issue by lvliming** [kailong321200875/vue-element-plus-admin#401]
我改了app.ts中layout='top'， 结果菜单栏的背景颜色不正确。不知道改什么地方，多谢，请求指点

**Comment by kailong321200875** [comment]
<img width="339" alt="image" src="https://github.com/kailong321200875/vue-element-plus-admin/assets/32283845/cf5e8014-c7e5-429b-acfa-554380ebf980">
弄好你的初始化配置化后，拷贝到appStore里面就行
