### ISSUE TITLE
mini分支下app的 IsDark 失效

### ISSUE THREAD

**Issue by tidycode** [kailong321200875/vue-element-plus-admin#403]
拉了mini 最新的代码（SHA  9eb1356c4e5dafae6a2a438a19a1316f06fc6ac1 ）
上版本反馈的 localstorage 中的 节点app 未存储，  [mini分支下缓存app失效]( https://github.com/kailong321200875/vue-element-plus-admin/issues/390) ，目前在这个版本已经修复了。

但是依然有个小问题，app下的 IsDark默认是true ，设置为 false  后 ,在页面刷新后 失效还是变成了 true。

该问题必复现。

**Comment by kailong321200875** [comment]
需要清空下缓存，默认配置才能生效

**Comment by tidycode** [comment]
一开始我也以为是cache 的问题，但是我最后定位如下：
1、在app.ts中 isdark默认是 false，
2、但是在 Mini 分支中，访问系统的时候却变成了 true，
3、登录完毕后，点击项目设置改为 false ，
4、在页面刷新后，应该是 false ，但实际变成了 true

最后定位在了App.vue中的代码，如下
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/5961374/d427fa98-64f0-4f31-a69d-8c38f6d9b0e5)

因为这段代码，导致了isDark一直设置为了true,但是在 master 分支App.vue如下
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/5961374/7eb4f9b0-022f-418a-ac61-32b2bb4af92b)

master 分支是设置成功的，初步判断是 master 的代码没有同步到 Mini 分支导致的

**Comment by tidycode** [comment]
提完评论后我发现在上午提交 issue 之后，master 分支又一次同步到了 Mini，现在 mini分支中App.vue和 master 已经保持一致了，isdark也能正确的设置了
