### ISSUE TITLE
Mini 分支下点击‘项目配置’会报错

### ISSUE THREAD

**Issue by tidycode** [kailong321200875/vue-element-plus-admin#404]
拉了mini 最新的代码（SHA  9eb1356c4e5dafae6a2a438a19a1316f06fc6ac1 ）

点击‘项目配置’，控制台会提示 Warn 级别错误
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/5961374/83ac609e-a9ed-4093-ba4a-5f6633590bc5)

[Vue warn]: getCurrentInstance() called inside a computed getter. This is incorrect usage as computed getters are not guaranteed to be executed with an active component instance. If you are using a composable inside a computed getter, move it ouside to the setup scope. 
  at <ElButton class="v-button color-#fff w-full" size=undefined type="primary"  ... > 
  at <Button type="primary" class="w-full" onClick=fn<copyConfig> > 
  at <ElFocusTrap loop="" trapped=true focus-trap-el= <div aria-modal=​"true" aria-labelledby=​"el-id-7871-5" aria-describedby=​"el-id-7871-6" class=​"el-drawer rtl open" role=​"dialog" style=​"width:​ 350px;​">​…​</div>​flex  ... > 
  at <ElOverlay mask=true overlay-class=undefined z-index=4000  ... > 
  at <BaseTransition onAfterEnter=fn<afterEnter> onAfterLeave=fn<afterLeave> onBeforeLeave=fn<beforeLeave>  ... > 
  at <Transition name="el-drawer-fade" onAfterEnter=fn<afterEnter> onAfterLeave=fn<afterLeave>  ... > 
  at <ElDrawer modelValue=true onUpdate:modelValue=fn direction="rtl"  ... > 
  at <Setting> 
  at <Layout class="" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {…} > > 
  at <RouterView class="" > 
  at <ElConfigProvider namespace="el" locale= {name: 'zh-cn', el: {…}} message= {max: 1}  ... > 
  at <ConfigGlobal size="default" > 
  at <App>

[Vue warn]: getCurrentInstance() called inside a computed getter. This is incorrect usage as computed getters are not guaranteed to be executed with an active component instance. If you are using a composable inside a computed getter, move it ouside to the setup scope. 
  at <ElButton class="v-button color-#fff w-full" size=undefined type="danger"  ... > 
  at <Button type="danger" class="w-full" onClick=fn<clear> > 
  at <ElFocusTrap loop="" trapped=true focus-trap-el= <div aria-modal=​"true" aria-labelledby=​"el-id-7871-5" aria-describedby=​"el-id-7871-6" class=​"el-drawer rtl open" role=​"dialog" style=​"width:​ 350px;​">​…​</div>​flex  ... > 
  at <ElOverlay mask=true overlay-class=undefined z-index=4000  ... > 
  at <BaseTransition onAfterEnter=fn<afterEnter> onAfterLeave=fn<afterLeave> onBeforeLeave=fn<beforeLeave>  ... > 
  at <Transition name="el-drawer-fade" onAfterEnter=fn<afterEnter> onAfterLeave=fn<afterLeave>  ... > 
  at <ElDrawer modelValue=true onUpdate:modelValue=fn direction="rtl"  ... > 
  at <Setting> 
  at <Layout class="" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< Proxy(Object) {…} > > 
  at <RouterView class="" > 
  at <ElConfigProvider namespace="el" locale= {name: 'zh-cn', el: {…}} message= {max: 1}  ... > 
  at <ConfigGlobal size="default" > 
  at <App>

**Comment by kailong321200875** [comment]
已修复
