### ISSUE TITLE
Mini分支下Search组件的select组件异常

### ISSUE THREAD

**Issue by tidycode** [kailong321200875/vue-element-plus-admin#411]
1、分别拉取 master 最新代码和拉取 Mini 最新代码（[67a202fef3fb70ae5b111296b125a0c077cd4a09](https://github.com/kailong321200875/vue-element-plus-admin/commit/67a202fef3fb70ae5b111296b125a0c077cd4a09)）

2、参考 master 页面中的 Components/Search.vue代码，在 Mini 新建一个界面，完整如下
```
<script setup lang="ts">
import { ContentWrap } from '@/components/ContentWrap'
import { Search } from '@/components/Search'
import { reactive } from 'vue'
import { FormSchema } from '@/components/Form'
const schema = reactive<FormSchema[]>([
  {
    field: 'field',
    label: '-select-',
    component: 'Select',
    componentProps: {
      options: [
        {
          label: 'option1',
          value: '111'
        },
        {
          label: 'option2',
          value: '222'
        }
      ]
    }
  }
])
</script>
<template>
  <Search :schema="schema" />
</template>
<style lang="less" scoped></style>
```

结果如下：
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/5961374/22072a86-5629-41e0-acf3-d777290bfa38)
明显异常

3、上述代码在 master 中是正常显示，如下
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/5961374/b6a80bb1-6618-48c5-bd45-6b396292ee68)

**Comment by kailong321200875** [comment]
element-plus的问题，可以先把版本固定要2.4.4，先不升级2.5版本

**Comment by tidycode** [comment]
固定在 2.4.4 确实是可以的了，但是不太明白 master 也是 2.5版本，为什么就正常的呢？
