### ISSUE TITLE
不建议使用5000端口，会和macOS 的 airplay 冲突

### ISSUE THREAD

**Issue by tidycode** [kailong321200875/vue-element-plus-admin#412]
最新代码中本地开发端口用的是 5000，实测会和macOS 的 airplay 应用冲突，导致项目冲突，
 lsof -P -n -i :5000  
COMMAND     PID   USER      FD   TYPE          DEVICE  SIZE/OFF    NODE   NAME
ControlCe    12345  demo      **    **                 ***                 0t0       TCP    *:5000 (LISTEN)
除非关掉airplay，否则该端口无法 kill 掉。

进一步可见：
[SEE](https://apple.stackexchange.com/questions/431154/should-controlcenter-app-listen-to-port-5000-tcp-on-a-normal-macos-monterey-syst)

**Comment by kailong321200875** [comment]
已处理
