### ISSUE TITLE
useSearch 中 getFormData 方法未给到预期值

### ISSUE THREAD

**Issue by zk0817** [kailong321200875/vue-element-plus-admin#427]
const { searchRegister, searchMethods } = useSearch()
const { getFormData: getSearchFormData } = searchMethods

const searchSchema = reactive<FormSchema[]>([
 // ...
])

getSearchFormData ()
// 预期：获得 Search 表单内数据
// 实际值：undefined

<Search :schema="searchSchema" @register="searchRegister" />

**Comment by jinnnyang** [comment]
我也与遇到了这个问题，而且用例中为啥只给创建，不给使用数据的代码
