### ISSUE TITLE
【bugs】InputPassword 无法获取到可用 ref，主题切换异常，tag-view affix 异常

### ISSUE THREAD

**Issue by yuanyxh** [kailong321200875/vue-element-plus-admin#432]
## Bugs

1. InputPassword 没有处理 ref 透传，无法调用 ElInput 暴露的方法
2. 默认主题下（菜单深色，内容亮色），切换 dark -> light 模式后，左侧菜单变为亮色，刷新后项目配置中头部主题与菜单主题未选中
3. route 设置 meta.affix 固定显示后，图标未展示

![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/72425622/4544b662-523a-405c-8619-49d9c0726d42)
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/72425622/91ac7e06-c3a0-4056-be6d-7f6380e90c0e)

**Comment by kailong321200875** [comment]
问题3已修复，1的话可以自行导出，2的话可以忽略，记这些状态会比较麻烦
