### ISSUE TITLE
使用useCrudScheme配置表单未正确不渲染

### ISSUE THREAD

**Issue by itisifin** [kailong321200875/vue-element-plus-admin#435]
hi，官网示例中的权限管理-部门管理内，示例中配置的为树形下拉框，并配置了API请求，但数据聚焦后并未展示为对应的下拉框。

尝试了下在form里面是OK的，详情如下图：

<img width="1530" alt="image" src="https://github.com/kailong321200875/vue-element-plus-admin/assets/162892504/b5911beb-ad38-45d9-89ab-230a13a03647">

**Comment by itisifin** [comment]
> hi，官网示例中的权限管理-部门管理内，示例中配置的为树形下拉框，并配置了API请求，但数据聚焦后并未展示为对应的下拉框。
> 
> 尝试了下在form里面是OK的，详情如下图：
> 
> <img alt="image" width="1530" src="https://private-user-images.githubusercontent.com/162892504/311513549-b5911beb-ad38-45d9-89ab-230a13a03647.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAwODE1MDcsIm5iZiI6MTcxMDA4MTIwNywicGF0aCI6Ii8xNjI4OTI1MDQvMzExNTEzNTQ5LWI1OTExYmViLWFkMzgtNDVkOS04OWFiLTIzMGExM2EwMzY0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMFQxNDMzMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODUxZGQyYWM0Yjc2NGJmOTVmOWMyY2NhODdiNTZhYzZhODA5ZTUwYTBkZjQ1NDFkNGUzOGI3YjU4NGExZjgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bjhakvw_x-NmCLT6RP1S7cheWAlsGGV-ljJElJdvEso">

找到原因了，useCrudSchemas 里面取值已经改为了 search， 但页面内配置的为 form 字段，导致取不到对应的 componentType，全部默认为了 input 组件

<img width="698" alt="image" src="https://github.com/kailong321200875/vue-element-plus-admin/assets/162892504/214663a9-e526-4314-aa3d-c4d77e33fd94">

**Comment by kailong321200875** [comment]
useCrudSchemas 本身配置的search和form字段就是为了针对不同组件来的，所以你应该卸载search字段中，如果嫌麻烦重复写，可以提取出来公用的部分
