### ISSUE TITLE
axios目录下的config.ts，service.ts均无法正常显示多语言。

### ISSUE THREAD

**Issue by P0164442** [kailong321200875/vue-element-plus-admin#436]
大佬你好，有个问题确认下，因为在去年的老框架中， 是可以在axios目录下的文件中正常提示多语言的。但是在现在的框架中不行。
以service.ts为例子， 写入：
import { useI18n } from '@/hooks/web/useI18n'
const { t } = useI18n()
然后代码中引入多语言如图1,在界面中显示如图2
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/74224722/14b5ea44-430b-489f-b832-172b2637ce34)
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/74224722/fd5a4a87-03b5-4ab6-b8e9-49dfce6e5c6c)

**Comment by kailong321200875** [comment]
<img width="565" alt="image" src="https://github.com/kailong321200875/vue-element-plus-admin/assets/32283845/7eacaa01-617c-42fc-b528-17adefdb2206">
把 const { t } = useI18n() 引入放到这边来就可以了
