### ISSUE TITLE
菜单管理  新增 dialog里面的菜单类型缺少默认值

### ISSUE THREAD

**Issue by sixiTr** [kailong321200875/vue-element-plus-admin#447]
之前在菜单管理 点击新增按钮 出现的dialog里面的菜单类型    之前是有默认值的 默认选中
或者点击现有数据的时候 编辑 也会选中当前菜单类型 但是目前这版消失了 应该是bug

**Comment by sixiTr** [comment]
![image](https://github.com/kailong321200875/vue-element-plus-admin/assets/41049309/0a596b70-7b8e-4ac6-89db-07275293e702)

**Comment by kailong321200875** [comment]
无法复现，也可能是因为element-plus升级到了2.6的问题，可以尝试着把，components/Form 里面的 useRenderCheckbox 和 useRenderRadio 替换一下最新的
