### ISSUE TITLE
表格固定列后，鼠标放表格任意位置上，上下滑动不了

### ISSUE THREAD

**Issue by fantasy118** [kailong321200875/vue-element-plus-admin#448]
![1711699493619](https://github.com/kailong321200875/vue-element-plus-admin/assets/55779811/e9d84757-4df5-4c37-8468-b0347abeb682)
表格第一列、第二列左侧固定，最后一列右固定，滑动表格时滑动不了，并且固定列上移出现错位现象

**Comment by kailong321200875** [comment]
无法复现，请提供更详细的例子

**Comment by QuestMi** [comment]
哈哈哈, 为啥都提供源代码了不直接提pr呢
