### ISSUE TITLE
创建动态路由后，访问自动跳转到404

### ISSUE THREAD

**Issue by kingname** [kailong321200875/vue-element-plus-admin#455]
1. 首先创建`src/views/Profile/info.vue`，把guide页面的源代码复制过去。
2. 在`src/router/index.ts`的asyncRouterMap中创建一个动态路由：

```js
{
    path: '/info',
    component: Layout,
    name: 'Info',
    meta: {},
    children: [
      {
        path: 'index',
        component: () => import('@/views/Profile/info.vue'),
        name: 'info',
        meta: {
          title: '用户信息' ,
          icon: 'cib:telegram-plane'
        }
      }
    ]
  },
```
保存并重启。无论是访问/info还是访问/info/index,全部都会 直接跳转到404页面

**Comment by kingname** [comment]
更离谱的是，我把asyncRouterMap清空了，保存然后重启，页面竟然还有全部的路由？？

页面左侧的导航栏，似乎跟这个src/router/index.ts没有任何关系。。。

<img width="1431" alt="image" src="https://github.com/kailong321200875/vue-element-plus-admin/assets/5440523/8714a6a1-dc03-413f-bf18-7d4c71bb40e9">

**Comment by kailong321200875** [comment]
https://element-plus-admin-doc.cn/guide/fqa.html#%E6%B7%BB%E5%8A%A0%E8%B7%AF%E7%94%B1%E4%B9%8B%E5%90%8E%EF%BC%8C%E9%A1%B5%E9%9D%A2%E6%97%A0%E6%B3%95%E5%B1%95%E7%A4%BA

**Comment by MengZ-super** [comment]
> https://element-plus-admin-doc.cn/guide/fqa.html#%E6%B7%BB%E5%8A%A0%E8%B7%AF%E7%94%B1%E4%B9%8B%E5%90%8E%EF%BC%8C%E9%A1%B5%E9%9D%A2%E6%97%A0%E6%B3%95%E5%B1%95%E7%A4%BA

没用啊 这什么鬼教程
