### ISSUE TITLE
表单组件中 如何添加Table ,BaseButton

### ISSUE THREAD

**Issue by nubigit** [kailong321200875/vue-element-plus-admin#508]
大佬们,  我想在Form 里面添加  table 组件,  而且 可以动态给表格 添加行 ,删除行,  表格中 各个列是可以编辑的input,或者checkBox 等 
这个要怎么扩展 Form 组件, 麻烦指点下  3q

我设置 表格的tableColumn  居然 ElInput 不能修改? 写大佬指点下 
`
 {
    field: 'fieldName',
    label: '字段名',
    align: 'center',
    slots: {
      default: (args: any) => {
        return (
          <ElInput
            onUpdate:modelValue={args.row.fieldName}
            modelValue={args.row.fieldName}
          ></ElInput>
        )
      }
    }
  }
`
![image](https://github.com/user-attachments/assets/f584c3b7-d433-4eae-90c0-d2812019e60c)

不给初始化值 ,还不让改吗?   而且看控制台 还有异常, 不知道是自己不会呢, 还是框架有问题?

**Comment by HWxing** [comment]
TSX写法的问题吧，试试ElInput加个onUpdate:modelValue={(value: string) => (args.row.fieldName = value)}
