### ISSUE TITLE
路由设置的icon图标不显示

### ISSUE THREAD

**Issue by KZ137onethe** [kailong321200875/vue-element-plus-admin#515]
我在mini分支上，新增了首页，在router/index.ts中的/dashboard设置了图标，如下：
![image](https://github.com/user-attachments/assets/501c9883-7b3f-4b36-b1ba-9461e8c719fe)
但是项目启动后，首页的图标不显示，如下：
![image](https://github.com/user-attachments/assets/e19f9614-3f4f-4550-bb91-211d465c3905)
我看了下项目文档和issues没有找到结果，作者可以解答下么？

**Comment by kailong321200875** [comment]
mini 分支代码没有同步，可以复制一下Icon组件的代码合uno.config.ts的代码

**Comment by KZ137onethe** [comment]
ok，解决了，谢谢喽

**Comment by HWxing** [comment]
> ok，解决了，谢谢喽

作者怎么解决的，我复制了icon组件的unos也不行

**Comment by KZ137onethe** [comment]
我有个变量改动了

**Comment by ShiLongTowngrass** [comment]
@KZ137onethe 是icon.vue的adminNamespace变量吗？
