### ISSUE TITLE
 pnpm run build:pro  打包卡在65%

### ISSUE THREAD

**Issue by ShiLongTowngrass** [kailong321200875/vue-element-plus-admin#556]
![be855b54243e3bb163f9b5c58e31307](https://github.com/user-attachments/assets/2c353ae6-6869-4ab5-b4de-bdde3d81c72e)
pnpm run pro是可以正常运行，但是build就卡住了

**Comment by sRoke** [comment]
怎么解决的？我也是卡死在65

**Comment by ColourfulU** [comment]
我也是
