### ISSUE TITLE
对于包含Upload的Form表单，我只能获取到Form的ref实例，但是获取不到内部组件Upload的实例，我想获取到Upload的实例然后手动调用submit，除了这种方法还有其他手动调用submit的方法吗

### ISSUE THREAD

**Issue by ohMylittlePig** [kailong321200875/vue-element-plus-admin#558]
<img width="529" alt="屏幕截图 2024-11-13 173613" src="https://github.com/user-attachments/assets/a03e9ef4-bb91-4421-b3e3-f55f7093d899">
框架是这样定义的，我找不到Upload实例的地方，只有
const elForm = await getElFormExpose()
获取Form的实例，怎么获取Upload组件的实例呢

**Comment by chaimHL** [comment]
所以是怎么获取的
