### ISSUE TITLE
如果路由某子菜单路径（path）名相同，那么菜单点击选择时会出现混乱

### ISSUE THREAD

**Issue by wxg4net** [kailong321200875/vue-element-plus-admin#62]
![2022-05-25_14-18-35](https://user-images.githubusercontent.com/1198284/170193429-7996068e-f40c-4a3a-a200-12482a8e9c19.png)
`const adminList = [
  {
    path: '/level',
    component: '#',
    redirect: '/level/menu1',
    name: 'Level',
    meta: {
      title: 'router.level',
      icon: 'carbon:skill-level-advanced'
    },
    children: [
      {
        path: 'menu1',
        name: 'Menu1',
        component: 'views/Level/Menu2',
        meta: {
          title: 'router.menu1'
        }
      },
      {
        path: 'menu2',
        name: 'Menu2Demo',
        component: 'views/Level/Menu2',
        meta: {
          title: 'router.menu2'
        }
      }
    ]
  },
    {
    path: '/level3',
    component: '#',
    redirect: '/level/menu1/menu1-1/menu1-1-1',
    name: 'Level3',
    meta: {
      title: 'router.level',
      icon: 'carbon:skill-level-advanced'
    },
    children: [
      {
        path: 'menu1',
        name: 'Menu13',
        component: 'views/Level/Menu2',
        meta: {
          title: 'router.menu1'
        }
      },
      {
        path: 'menu2',
        name: 'Menu23Demo',
        component: 'views/Level/Menu2',
        meta: {
          title: 'router.menu2'
        }
      }
    ]
  }
]`

**Comment by wxg4net** [comment]
问题大概出在 函数 getAllParentPath<AppRouteRecordRaw>(allRouters, v.path) 的实现上
根据自己的编码习惯，既然name一定不能重复，那就用name做一个判断吧
name命名以parentName值开头即可，
export const getAllParentPath = <T = Recordable>(treeData: T[], route: AppRouteRecordRaw) => {
  const menuList = findPath(
    treeData,
    (n) => route.name.startsWith(n.name) && n.path === route.path
  ) as AppRouteRecordRaw[]
  return (menuList || []).map((item) => item.path)
}

**Comment by silverbasilisk** [comment]
@wxg4net, Excellent!
I met the same issue and just fixed with your advice.
Thank you.
