### ISSUE TITLE
表格组件如何实现数据不在显示列，但是在编辑或者搜索里面出现

### ISSUE THREAD

**Issue by wxg4net** [kailong321200875/vue-element-plus-admin#64]
请教作者
比如 用户列表密码项， 页面不用显示，但是编辑里面可以出现。
另外某个列数据如果使用自定义组件，有没有案例可供参考
谢谢

**Comment by kailong321200875** [comment]
表格组件有个setProps方法，可以使用这个去控制，如果需要使用自定义组件，可以参考下操作列

**Comment by wxg4net** [comment]
已解决
第一个问题，可以用
const extraSchema: FormSchema[] = [
  {
    field: 'categoryId',
    label: '分类',
    value: null,
    component: 'ProductCategoryTreeComponent'
  }
]
const { allSchemas } = useCrudSchemas(crudSchemas)
allSchemas.searchSchema.push(...extraSchema)
allSchemas.formSchema.push(...extraSchema)
第二个问题，文档在这里
文档 https://element-plus-admin-doc.cn/components/form.html#form-%E6%96%B9%E6%B3%95

**Comment by wxg4net** [comment]
已解决
第一个问题，可以用
const extraSchema: FormSchema[] = [
  {
    field: 'categoryId',
    label: '分类',
    value: null,
    component: 'ProductCategoryTreeComponent'
  }
]
const { allSchemas } = useCrudSchemas(crudSchemas)
allSchemas.searchSchema.push(...extraSchema)
allSchemas.formSchema.push(...extraSchema)
第二个问题，文档在这里
文档 https://element-plus-admin-doc.cn/components/form.html#form-%E6%96%B9%E6%B3%95
