### ISSUE TITLE
prettier not work

### ISSUE THREAD

**Issue by kurt-liao** [kailong321200875/vue-element-plus-admin#67]
prettier is not working.

It always tell me that it cannot format 'xxx' files, like the pic below.
![prettier](https://user-images.githubusercontent.com/32745146/172100015-9e131331-1b25-49b5-86be-18bbc033a387.png)

I've try my other projects, and they all work fine, so I do not think it is vscode error or prettier settings error.

**Comment by kurt-liao** [comment]
Sorry, it is my mistake.

There are nested folder in my vscode editor, and .prettierrc file is not at root.

**Comment by silverbasilisk** [comment]
Hi @kurt-liao 
I've installed prettier extension in my vscode but it's not working in this template.
I've checked in other projects but well.
First of all, I can't find prettier in formatter list.

![image](https://user-images.githubusercontent.com/103615256/176398047-61b226b9-a110-4b76-82fe-89973ef7b3b6.png)

How can I fix?

**Comment by kurt-liao** [comment]
Hi @lacmansoftware

I think the problem is in settings.json file in .vscode folder.
Since the repo author set prettier disabled.
 
![line_20220629_214300](https://user-images.githubusercontent.com/32745146/176451423-6a9dd0dd-e72c-4fef-9ac7-714c362eacc8.png)

You can try to delete .vscode folder and just use your own vscode settings.

This setting has use eslint to fix format, so maybe the prettier is unnecessary.

**Comment by silverbasilisk** [comment]
Thank  you.

![image](https://user-images.githubusercontent.com/103615256/176453672-dbf4300a-bb83-4874-8230-88b0042cf6e0.png)

I just changed prettier.enable as true and it's working.
