### ISSUE TITLE
如果不同的菜单，需要渲染同一个组件只是参数不一致，该如何处理，路由设置怎么做比较好？name与组件不一致时也无法缓存

### ISSUE THREAD

**Issue by megamew** [kailong321200875/vue-element-plus-admin#71]
谢谢

**Comment by kailong321200875** [comment]
你可以在包裹一层，路由菜单还是分离，比如叫做 router1 和 router2，router1 和router2 都有引入比如componentA这个组件，这样子，就可以去设置 router1 和 router2 是不是要缓存了。

**Comment by megamew** [comment]
export const asyncRouterMap: AppRouteRecordRaw[] = [
  {
    path: '/product',
    component: Layout,
    redirect: '/product/xx',
    name: 'Level',
    meta: {
      title: t('router.level'),
      icon: 'carbon:skill-level-advanced'
    },
    children: [
      {
        path: 'y',
        name: 'Menu3',
        component: () => import('@/views/Level/Menu12.vue'),
        meta: {
          title: t('router.menu2')
        }
      },
      {
        path: 'z',
        name: 'Menu4',
        component: () => import('@/views/Level/Menu12.vue'),
        meta: {
          title: 'ddd'
        }
      }
    ]
  }
]
是这个意思吗？demo能不能加一个例子，有点懵逼。谢谢。

**Comment by megamew** [comment]
宏观金融
       股指
       原油
黑色板块
       铁矿石
       螺纹钢
      ..............
农产品
     豆粕
     .........


大概结构就是这样，菜单数量比较多，页面只是传的参数不一样

**Comment by kailong321200875** [comment]
@megamew 目前好像只能这样

**Comment by wiexin** [comment]
如果两个都要缓存 那不就不满足框架缓存的条件了吗

路由设置 name，且不能重复
路由对应的组件加上 name，与路由设置的 name 保持一致
