### ISSUE TITLE
登陆逻辑怎么样的？如何在header中添加token？

### ISSUE THREAD

**Issue by X-Mars** [kailong321200875/vue-element-plus-admin#72]
如题 谢谢大佬

**Comment by kailong321200875** [comment]
![image](https://user-images.githubusercontent.com/32283845/173573421-b4862c3e-dc36-4afe-bd27-45dbd3657386.png)
可以在这边去添加token

**Comment by X-Mars** [comment]
感谢大佬已经加上token了
还有个问题
```
http://localhost/api/role/list/?roleName=admin
```
这个接口应该返回什么数据？什么格式呢？

**Comment by X-Mars** [comment]
```

**Comment by diorslau** [comment]
你是怎么加的啊
