### ISSUE TITLE
路由相关的问题

### ISSUE THREAD

**Issue by ALiftTime** [kailong321200875/vue-element-plus-admin#73]
作者您好,我有两个路由问题,向您请教

1. 生成的嵌套路由的问题
  为什么使用  createRouter 生成二级路由
   ```
   // 文件地址:  utils/routerHelper.ts
  const promoteRouteLevel = (route: AppRouteRecordRaw) => {
      let router: Router | null = createRouter({
        routes: [route as unknown as RouteRecordNormalized],
        history: createWebHashHistory()
      })
     .....
  }
  ```
2. 用 createRouter 生成的路由有个问题, 
     二级及更深的路由的 path 属性的设置, 不能 '/menu1', 只能 'menu1'
     如果是 '/menu1' 这样的路径, 生成的路由就不是全路径了,页面就读取不到这个路由了
     这是忘记对这块进行处理了吗?

感谢您看我的问题~

**Comment by kailong321200875** [comment]
因为如果嵌套多层没有处理的话，路由缓存在深层级下是没有办法生效的，所以现在多层级的路由都被处理成最多只有二级路由。问题二，这个是很合理的，如果加了/，就代表他就是一个全新的路由path，而不是当前的子路由。
