### ISSUE TITLE
表格嵌入el-button不展示

### ISSUE THREAD

**Issue by go-caipu** [kailong321200875/vue-element-plus-admin#74]
你们好，不知道为什么el-table-column 里面添加的按钮并不展示在页面上，单独添加的按钮是可以展示的，不知道是为什么。
页面展示如图：
![image](https://user-images.githubusercontent.com/7524530/173964001-d5dffcfc-b6a3-476e-b95f-270ea902fbed.png)

代码：
``  <el-table-column label="操作" align="left" class-name="small-padding fixed-width" width="260">
        <template #action="{ row }">
          <el-button>Default</el-button>
          <el-button type="text" icon="el-icon-edit" @click="handleUpdate(row)">修改</el-button>
          <el-button type="text" icon="el-icon-circle-check" @click="handleDataScope(row)"
            >数据权限</el-button
          >
          <el-button
            v-if="row.roleId > 2"
            type="text"
            icon="el-icon-delete"
            @click="handleDelete(row)"
            >删除</el-button
          >
        </template>
      </el-table-column>``

**Comment by kailong321200875** [comment]
如果是用封装的Table组件的话，参考下在线例子的用法，你这个用法不太对

**Comment by go-caipu** [comment]
感谢你的回复，现在我是把现有功能迁移到这个框架下，如果要再用封装table组件工作量较大，这个功能之前在别的框架下是能正常展示按钮的。

**Comment by kailong321200875** [comment]
有没有可能是element-plus的版本不对齐，你可以查看下现在这个框架版本，然后查看对应的element-plus的api
