### ISSUE TITLE
作者您好

### ISSUE THREAD

**Issue by ALiftTime** [kailong321200875/vue-element-plus-admin#77]
我根据您的模板做了一套, vuecli 并且没有使用 ts 开发的模板,不知道是否有机会, 可以给您看一下?

**Comment by kailong321200875** [comment]
可以的

**Comment by ALiftTime** [comment]
我代码提交了, 您有时间可以查看一下

**Comment by ALiftTime** [comment]
您有时间可以帮我提一些意见吗? 我fork了

**Comment by kailong321200875** [comment]
我看了一下，发现整体都很不错的，暂时没有发现什么需要改动的地方，并且有些地方处理得比我好，自己这边也可以借鉴一下。

**Comment by ALiftTime** [comment]
收到, 感谢,  以后还是需要向您多多学习

**Comment by ALiftTime** [comment]
我这个想法,主要是用来贴近开发者做的一些思路

**Comment by ALiftTime** [comment]
针对于,二三线城市初级开发者,减少了一些学习成本

**Comment by ALiftTime** [comment]
但是,和您的初衷"学习一些新的东西",又不是特别的贴近,  比较尴尬

**Comment by ALiftTime** [comment]
还有就是,我在使用 vuecli 的时候,遇到了这几个问题,我没能解决,不知道您有没有好的解决方案

1. 暂不能使用 Iconify 图标, Iconify 在cli中无法动态生成图标
2. 我的mock.js, 使用的是webpack devServer, 但是我觉得这种方案是一种骚操作, 应该是场景不满足的,但是我想不到,我唯一想到场景不满足的是,生产环境不能使用,但是我又觉得,mock基本上是开发阶段,才会需要,所以这块我是很纠结的

**Comment by kailong321200875** [comment]
1的话，我暂时没试验过，可以查查看有没有相关方面的插件 
2的话，其实可以直接使用mockjs，这样可以在开发和生产保持一致

然后其他的，还是看需求，业务稳定，用得舒服才是最重要的。

**Comment by ALiftTime** [comment]
是的
