### ISSUE TITLE
How to pass value to form component?

### ISSUE THREAD

**Issue by hung-applicaa** [kailong321200875/vue-element-plus-admin#80]
I want to pass value to different components not only the textbox. For e.g: CheckBox or ComboBox...
I checked the example and it's fixed values

https://github.com/kailong321200875/vue-element-plus-admin/blob/7fb38b9693dae252273e0871249ef8c0b7d123a3/src/views/Example/Dialog/ExampleDialog.vue#L93

**Comment by kailong321200875** [comment]
you can use setProps
