### ISSUE TITLE
Response is undefined in api

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#81]
Hello @kailong321200875 
This is amazing open source template with Vite and Elementplus.
Thank you for your effort.

And I have an issue.
I always get undefined response when I make a request in api.
```
// api/login/index.ts
export const loginApi = async (data: UserLoginType): Promise<IResponse> => {
  const res = await request.post({
    url: '/index/login/system',
    headersType: 'application/x-www-form-urlencoded',
    data
  })
  console.log('in api: ', res)
  // this returns undefined. but there's correct response when I checked in console.
  return res && res.data
}

```

```
// vite.config.ts
    ...
    server: {
      port: 4000,
      proxy: {
        // 选项写法
        '/api': {
          target: 'http://35.194.244.237:9998',
          changeOrigin: true,
          rewrite: path => path.replace(/^\/api/, '')
        }
      },
      hmr: {
        overlay: false
      },
      host: '0.0.0.0'
    },
   ...
```

![image](https://user-images.githubusercontent.com/103615256/176123784-eac43157-47e3-40a4-8d83-c80990633eaf.png)

![image](https://user-images.githubusercontent.com/103615256/176123890-bd8199cd-8133-4bb8-ac63-f3e97f545025.png)

![image](https://user-images.githubusercontent.com/103615256/176123938-8c8508a6-f23a-4074-9bed-146234cace0c.png)

![image](https://user-images.githubusercontent.com/103615256/176124281-11f10a74-38d3-42da-8d77-773f50c20a49.png)

I also tried with sample api link for test.
https://jsonplaceholder.typicode.com/todos/1
But the result is the same.

How can I fix this?

**Comment by kailong321200875** [comment]
<img width="605" alt="image" src="https://user-images.githubusercontent.com/32283845/176125647-09760523-bee6-45fb-a12c-c3a62da67db5.png">
you can try it
result_code: '0000' => result_code: 0

**Comment by kailong321200875** [comment]
src/config/axions/config.ts

**Comment by silverbasilisk** [comment]
Oh, cool.
It's fixed.
I am just starting my project using this template and will may be tons of issues.
And regret to saying that I'll disturb you with many questions.

Thank you
Best regards.
👍
