### ISSUE TITLE
How to clear cache and go to login page when session is expired in backend side?

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#82]
Hello @kailong321200875 
I'm just developing frontend side using this template and have 401 error code in response when the session is expired in backend side.
The backend is not editable so I handle response and logout manually.
I think the code will be here.

```
// config/axios/index.ts
// response 拦截器
service.interceptors.response.use(
  (response: AxiosResponse<Recordable>) => {
    if (response.data.code === result_code) {
      return response
    } else {
      ElMessage.error(response.data.msg)

      // handle here. Expected code will be here I think.....
      if (response.data.code === 401 && response.data.msg === '登陆过期！') {
        wsCache.clear()
        tagsViewStore.delAllViews()
        resetRouter() // 重置静态路由表
        router.replace('/login')
      }
    }
  },
  (error: AxiosError) => {
    console.log('err' + error) // for debug
    ElMessage.error(error.message)
    return Promise.reject(error)
  }
)

```
But it's not working.
How can I fix this?
Sorry for asking basic question.

**Comment by kailong321200875** [comment]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/32283845/176329471-6d59c2cc-b302-4697-81bd-4d129e742f6e.png">

you can try this

**Comment by silverbasilisk** [comment]
Hi @kailong321200875 
I tried along your tip and nearly fixed this issue.
But it just replaces url on browser link, not execute.
So I add `location.reload()` statement manually. I know it's not good solution.
`src/config/axios/index.ts`
![image](https://user-images.githubusercontent.com/103615256/176732093-382ea23a-8f26-4a5d-9c28-f6f515b556d0.png)

How can I fix?
