### ISSUE TITLE
Dialog和Form表单配合使用问题

### ISSUE THREAD

**Issue by 2624431797** [kailong321200875/vue-element-plus-admin#83]
作者您好，首先非常感谢你的这一套项目，对于我们帮助很大
如今我遇到这样一个问题，就是Dialog组件和Form配合使用时会报错
The form is not registered. Please use the register method to register
按照你给的例子分开，将Form当成一个组件不会报错，但实际在开发中往往有时写在一起会更方便一些，不知道这个问题是设计如此还是存在的问题呢

**Comment by 2624431797** [comment]
![image](https://user-images.githubusercontent.com/54942617/176368426-46782399-c119-4460-8d29-dbed5d7c42e7.png)

**Comment by kailong321200875** [comment]
这两个是都叫formRegister吗
<img width="658" alt="image" src="https://user-images.githubusercontent.com/32283845/176391748-b397f4d0-14dc-4090-b888-2cce2362f717.png">

**Comment by 2624431797** [comment]
和Table的函数名重复 起的别名
![image](https://user-images.githubusercontent.com/54942617/176393272-4717a60e-4e1a-4043-9ef1-e71cc7f1b641.png)

**Comment by kailong321200875** [comment]
这个讲道理不应该，我找个时间调试看看

**Comment by 2624431797** [comment]
![image](https://user-images.githubusercontent.com/54942617/176409171-64ffd339-b260-4ddc-969e-41e20599f255.png)
稍微排查了一下 发现在form的vue文件夹中，在mounted执行的该方法但奇怪的是我在代码中加了v-if，按说应该加了后不再触发mounted中的方法
![image](https://user-images.githubusercontent.com/54942617/176409728-d95ac59c-f568-4e1d-93c7-b5667d11e8e6.png)
导致页面报错并且无DOM渲染出来
![image](https://user-images.githubusercontent.com/54942617/176410126-c1c275ee-517c-4c8b-8910-541ea9f0eba6.png)

**Comment by kailong321200875** [comment]
这可能是个BUG，我找个时间修复下看看，实在不好意思，可能要耽误几天，或者你要是有解决方案的话，欢迎提PR

**Comment by kailong321200875** [comment]
由于dialog的特殊性，没办法使用useForm，只能使用refForm，具体可以看下例子https://element-plus-admin.cn/#/components/dialog 或者 像综合示例那样，包裹一层组件 https://element-plus-admin.cn/#/example/example-dialog
