### ISSUE TITLE
Which format extension should I use in this template?

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#85]
Hello @kailong321200875 
Thank you for your kind response.
Those are the most helpful for me.
Thank you again.

And I got another issue and here is.
It's just code formatting problem.
1. I enjoy using prettier for code formatting and it's working well in other projects and also checked now.
but it's not working in this template.
I can't find that in formatter list, like following.
![image](https://user-images.githubusercontent.com/103615256/176399206-de453eca-7479-4ff1-986d-8d68e5b518d6.png)
How can I fix this?

2. Why is this error occurred?
![image](https://user-images.githubusercontent.com/103615256/176399516-a5514275-fbbb-43a1-b89b-453ab0f06775.png)
It's just code format error(eslint related) and possible to affect project running?
What formatter extension should I use fix this formatting error automatically in vscode?

**Comment by kailong321200875** [comment]
you can install Volar

**Comment by silverbasilisk** [comment]
I know.
I've already installed volar but it's working badly.
Look.
![image](https://user-images.githubusercontent.com/103615256/176408226-48c0b14c-0303-4628-b920-571fa286d418.png)

After formatted using Volar, it's changed like this.
![image](https://user-images.githubusercontent.com/103615256/176408460-de7eecdd-81df-4fb8-a51d-1f921b2ee7cf.png)
But this says errors like above.
What's wrong?

**Comment by kailong321200875** [comment]
install prettier， you can use Configure Default Fromatter and select Prettier code formatter

**Comment by silverbasilisk** [comment]
https://github.com/kailong321200875/vue-element-plus-admin/issues/67#issuecomment-1170004969

It's fixed by @kurt-liao
