### ISSUE TITLE
怎么在本地代理配置，vite.config.ts

### ISSUE THREAD

**Issue by wenlongFam** [kailong321200875/vue-element-plus-admin#86]
怎么在本地代理配置，vite.config.ts
以下代码一直在404错误：
`    server: {
      proxy: {
        // 选项写法
        '/api': {
          target: 'http://47.***.***.***',
          changeOrigin: true,
          rewrite: path => path.replace(/^\/api/, '')
        }
      },
      hmr: {
        overlay: false
      },
      host: '0.0.0.0'
    },`

**Comment by kailong321200875** [comment]
配置完成之后，需要在src/config/axios/config.ts中，在base填写 /api，这样才会生效
