### ISSUE TITLE
How to pass placeholder in schema to show input in Search.

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#87]
Hello @kailong321200875 
I'd like to show placeholder in input in search and pass string on schema.
But I can't find any props in form schema.

![image](https://user-images.githubusercontent.com/103615256/176461089-7af312bf-39f3-4314-a415-36fc1c3ccf1b.png)

![image](https://user-images.githubusercontent.com/103615256/176461158-20c0e8ed-1a52-45c9-bf4f-7ddae7baa7b7.png)

How can I fix?

**Comment by kailong321200875** [comment]
you can try this  {
  filed: 'xxx',
  componentProps: {
    placeholder: xxxx
  }
}

**Comment by silverbasilisk** [comment]
Awesome.
Thank you.
