### ISSUE TITLE
Can I make select component load its options from api by editing schema?

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#88]
Hello @kailong321200875 
I have search bar with input and select components.
No problems in input but not in select.
Now I'm updating my previous version using this template and it's load options from backend originally.
I'd like to establish this function by editing search schema.

![image](https://user-images.githubusercontent.com/103615256/176467264-d01895d2-7aa2-450f-977c-7be065136525.png)

Just want to set componentProps using link of api from backend.
Like this one.

`componentsProps: '/sys/dict/option-list'`

Is this possible?

**Comment by kailong321200875** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/32283845/176571150-d3cb7c5d-f8b2-46e4-a82b-527ab253cb3f.png">

**Comment by silverbasilisk** [comment]
Hello @kailong321200875 
Thank you for your response.
I tried but still have an issue.

![image](https://user-images.githubusercontent.com/103615256/176637348-561261a9-9efd-4473-ac89-eb17571aa8ec.png)

![image](https://user-images.githubusercontent.com/103615256/176637393-28b16619-e2b0-4212-8a9c-d2ce4e1236a2.png)

But it's not working.
What's wrong with this?

**Comment by kailong321200875** [comment]
sorry，this may be a series of problems caused by relying on updates. I need some time to deal with them

**Comment by silverbasilisk** [comment]
No worries.
I believe it will come soon.
And I took ref as a solution.
Like this one.

![image](https://user-images.githubusercontent.com/103615256/176732954-1acada3a-833f-4d90-9594-4bf67c91ceb8.png)

`in crud schema`
![image](https://user-images.githubusercontent.com/103615256/176733115-d4e19760-1e7d-4296-a768-1294eafd88b5.png)

Actually it's working well now but I'd like to use `store` as `reactive` to share between several components.
But it's not working when it's used like this one.

![image](https://user-images.githubusercontent.com/103615256/176733975-dd8a6fa7-e667-46f3-a4ad-86796602be1d.png)

No errors and no shows.
How can I fix this?

**Comment by kailong321200875** [comment]
If you have a public global dictionary, please refer to src/permission.ts，look at lines 33 to 45

**Comment by kailong321200875** [comment]
if you use useCrudSchemas，you can see https://element-plus-admin.cn/#/hooks/useCrudSchemas and https://element-plus-admin-doc.cn/hooks/useCrudSchemas.html
