### ISSUE TITLE
在api目录同级，新建api_base目录放入从swagger生成的接口文件，为什么报错404？

### ISSUE THREAD

**Issue by wenlongFam** [kailong321200875/vue-element-plus-admin#89]
您好：
在api目录同级，新建api_base目录放入从swagger生成的接口文件，为什么报错404？
![image](https://user-images.githubusercontent.com/45864590/176583940-65fcccb1-7ead-4a7d-a527-52182e70a67c.png)

1，vite.config.ts配置了域名，
![image](https://user-images.githubusercontent.com/45864590/176583850-2f02972b-640d-4557-8666-8a58efc7c6db.png)

2，src/config/axios/config.ts也配置了域名
![image](https://user-images.githubusercontent.com/45864590/176583875-ff6f541d-4fa1-4861-a759-87e428c114c6.png)

**Comment by kailong321200875** [comment]
base 请换成 base: '/api'

**Comment by wenlongFam** [comment]
![image](https://user-images.githubusercontent.com/45864590/176590127-02e70038-dfcc-4d24-974e-fa2ac67df20f.png)
这样也不行，如下图：
![image](https://user-images.githubusercontent.com/45864590/176590346-29041d15-9caa-4c78-b12c-f929cb549a06.png)

**Comment by wenlongFam** [comment]
您好，demo下载到本地电脑运行时，登录和其他接口的代理代码是在哪里？
vite.config.ts里的proxy代码是注释的，所以目前找不到默认接口的代理是在哪？
