### ISSUE TITLE
Can I use different "label" in form and table in CRUD Schema?

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#92]
Hello @kailong321200875 
I'd like to use a default label and another label in form.
I tried like following but not working.
![image](https://user-images.githubusercontent.com/103615256/176748421-3c69ce7d-8a10-4734-afb8-5d3f2cc6f5ef.png)
Can I fix this?

**Comment by kailong321200875** [comment]
Good idea. I can modify it

**Comment by kailong321200875** [comment]
update 1.5.1
