### ISSUE TITLE
'span' in 'select' is not working

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#93]
Hello @kailong321200875 
I use span to set grid in select component in crud schema but is not working.
```
  {
    field: 'isMarried',
    label: '婚姻狀況',
    form: {
      component: 'Select',
      colProps: {
        span: 8
      },
      show: true
    },
    table: {
      show: false
    }
  },
```
The result is like this one.
![image](https://user-images.githubusercontent.com/103615256/176802171-2300f92c-0b82-4347-a4ba-fa21167c7f18.png)

Actually it's working well in Input but not others including DatePicker.
How can I fix?

**Comment by kailong321200875** [comment]
use componentProps: { style: { width: '100%' } }

**Comment by silverbasilisk** [comment]
> use componentProps: { style: { width: '100%' } }

Hi @kailong321200875 
It's not working.
No changes.

**Comment by LuckyArdhika** [comment]
For someone who uses this fvking template but has this problem and you don't have fix anywhere. try this one

using class and style combination,

```
componentProps: {
      style: {
        width: '100%'
      },
      class: 'pw-100',
}
```

style:
```
.pw-100 > .el-input__wrapper {
  width: 100%
}
```
