### ISSUE TITLE
Can I exchange position of label and input in schema? and custom size of label?

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#94]
Hello @kailong321200875 
I'd like to use Crud schema for Input component with a label right and custom size. Like in this image.
![image](https://user-images.githubusercontent.com/103615256/176802679-1ad9d9b9-5272-432c-81cc-8a655d9b135a.png)

I just tried like this one.
```
  {
    field: 'hasChild',
    label: '生育情況',
    form: {
      component: 'Select',
      colProps: {
        span: 4
      },
      show: true
    },
    table: {
      show: false
    }
  },
  {
    field: 'boyNum',
    label: '',
    form: {
      component: 'Input',
      colProps: {
        span: 2
      },
      show: true
    },
    table: {
      show: false
    }
  },
  {
    field: 'girlNum',
    label: '',
    form: {
      component: 'Input',
      colProps: {
        span: 2
      },
      show: true
    },
    table: {
      show: false
    }
  },
```
The result is like this.
![image](https://user-images.githubusercontent.com/103615256/176802760-b63691bc-ca28-4f26-91b0-f623a8cee349.png)

I should fix this but how can?

**Comment by kailong321200875** [comment]
see src/views/Login/components/RegisterForm.vue, you can customize your presentation by referring to the verification code

**Comment by silverbasilisk** [comment]
Hello @kailong321200875 
Would you like to help me fix this issue?
https://github.com/kailong321200875/vue-element-plus-admin/issues/82#issuecomment-1171447176
