### ISSUE TITLE
How to use component without any label

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#97]
Hello @kailong321200875 
I'd like to use any component without any label like following.
![image](https://user-images.githubusercontent.com/103615256/176895643-c0e83b32-97e3-4b0a-bc41-3abf92965ae5.png)

**Comment by kailong321200875** [comment]
you need use slot
![image](https://user-images.githubusercontent.com/32283845/176913776-3c6fcdcd-d55f-43c1-a7ba-ac76b41809be.png)
![image](https://user-images.githubusercontent.com/32283845/176913835-b2ef8830-80c3-431d-9575-5cc092f67ee6.png)
