### ISSUE TITLE
Select component width is still not working.

### ISSUE THREAD

**Issue by silverbasilisk** [kailong321200875/vue-element-plus-admin#98]
Hello @kailong321200875 
I used this statement to fix select component width but not working yet. No changes.
![image](https://user-images.githubusercontent.com/103615256/176896097-f59fe178-5d3f-4d2d-9d16-e42934f67203.png)

**Comment by kailong321200875** [comment]
update 1.5.3
If it is a search component, please set is-col: true，inline: false ，and set componentProps: { style: { width: '100%' } } 
![image](https://user-images.githubusercontent.com/32283845/176911569-0e26a29e-f277-422c-8c55-78cd0198466c.png)
